### ISSUE TITLE
Error decoding frame: Invalid data found when processing input

### ISSUE THREAD

**Issue by dpieski** [simon987/sist2#10]
Does this error mean that it is trying to process a file that it cannot read like a media file?

I am running this on a folder with a multitude of various file types, but I am getting this error fairly consistently for the past 7% or so and I am pretty certain that media files are less than 7% of my files.

Is there an error log so I can see what files it has the Errors on?

Also - is the percent based on storage volume or file quantity?

**Comment by simon987** [comment]
This means it couldn't read a frame from a media file (audio, video, image etc). This can happen for a bunch of reasons but there's not a whole lot you can do about it. This only means that this file in particular will not have a thumbnail generated for it.

You can generate this error by truncating a video in half or by renaming a `.zip` file to `.mp4` for example.

The percent is based on the number of files scanned divided by the number of files to scan. It doesn't scan in any particular order so you can't really guess what file it's scanning only based on the %.

**Comment by dpieski** [comment]
Does it have a "Completed Successfully" line at the end by chance? I didn't see it in the code but it has been a while since I have read C.

This is what I came in to this morning: 
![image](https://user-images.githubusercontent.com/3300522/71089811-36070800-2167-11ea-9ad4-78ce48191df2.png)

**Comment by dpieski** [comment]
Never mind. My bad. Ran out of memory.

```
 kernel: Out of memory: Kill process 977 (sist2) score 812 or sacrifice child
 kernel: oom_reaper: reaped process 977 (sist2), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

Thanks for your patience.

**Comment by simon987** [comment]
No worries.
For future reference, it should have the full bar (displays 100%) and a newline character when it's done

**Comment by dpieski** [comment]
Awesome! Thanks for your work on this.
