### ISSUE TITLE
Connect to elasticsearch with username, password and SSL support

### ISSUE THREAD

**Issue by germainm** [simon987/sist2#108]
sist2 version: 2.8.2

Platform (Linux or Docker, x86-64 or arm64): Linux, x86-64

Elasticsearch version:7.5.1

Command with arguments:  ./sist2_debug --bind=172.28.193.57:4090 --es-url=https://sist2:sist2@private.searchevolution.com:9200 web ~/.docs_idx

it seems there's no option for secured elasticsearch (username:password) and no support for https

my elasticsearch respond not a ssl/tls record

is there a way to specify es username/password other than in the url ?  is there's support for ssl to connect to an es host?

thanks

**Comment by simon987** [comment]
Hi, currently there is no support for HTTPS or username/password for elasticsearch within the `web` module

When I have free time I'll try to implement that feature

**Comment by germainm** [comment]
No problem.  Personally,  I use searchguard for securing elasticsearch.

Regards,

Germain

**Comment by simon987** [comment]
Should be fixed in v2.8.3, please let me know if it works with 'searchguard' @germainm

**Comment by germainm** [comment]
Yep,  was able to index a simple directory. (after given some permissions to the user). ask me for help if necessary.

I dislike needing to specify the user and password with --es-url (for security considerations : someone could get the password by listing the processes). config file would be better

**Comment by simon987** [comment]
Okay thank you for confirming.
You can create another issue for the other thing you brought up, but as of right now the security concerns are not convincing enough for me to implement loading from config
