### ISSUE TITLE
read/open: "No such file or directory" for files with single quotation mark or en dash in file path/name

### ISSUE THREAD

**Issue by dpieski** [simon987/sist2#11]
I received a few "open: No such file or directory" and "read:no such file or directory" errors. 

The commonality between all the files was a question mark in the error file name. Looking at the source files, the ? was substituted in place of either single quotation marks or en dashes.

I identified the character by copying it and pasting it in https://www.mclean.net.nz/ucf/
which returned U+2019 right single quotation mark, U+2018 left single quotation mark, and en dash U+2013.

**Comment by dpieski** [comment]
Also trademark sign U+2122

**Comment by simon987** [comment]
Hm that's weird. Can you paste an example file name for me? I'll try to figure this out this weekend.
Thanks a lot for taking the time to report this error!

**Comment by dpieski** [comment]
These are the only two file names I remembered and my history wont scroll further:

2017.9.5 Email string re domain purchase - RE_ We’ve completed your .uk registrant transfer.pdf

Office Communication re IDS cons’d

--
In the error it would show up like "Office Communication re IDS cons?d"

**Comment by dpieski** [comment]
Ran across this, it may help with the above issue.
https://stackoverflow.com/questions/28172022/character-encoding-of-microsoft-word-doc-and-docx-files

**Comment by dpieski** [comment]
another partial name:
439 – Final Office

**Comment by simon987** [comment]
I'm not able to reproduce the problem on my machine, what OS is your host machine?

**Comment by dpieski** [comment]
So, the files are hosted on a MS Windows Server 2016.
I am running Docker Desktop (Kernel Version: 4.9.184-linuxkit, Operating System: Docker Desktop, OSType: linux, Architecture: x86_64) on my Windows 10 Pro desktop. 

The Volume is mounted by: `docker volume create --driver local --opt type=cifs --opt device=//IP-ADDR/folders/ --opt o=user=USERNAME,domain=MYDOMAIN,password=MYPASS mydockervolume`

I could send you a sample file, however, I would not want to post it publically.

**Comment by simon987** [comment]
Ok now I'm pretty sure that this is a docker/locale issue (related to this: moby/moby#36616), for the next release I'll change the image locale to UTF8 and see if it fixes the problem

**Comment by simon987** [comment]
@dpieski Please let me know if you still get this error in `v1.2.4`, thank you!

**Comment by dpieski** [comment]
@simon987  Sist v1.2.9
I am still getting some of these errors. 

Looks like they are from parse.c line 11 error then the line 40 error. So I get:

```
open(): [2] No such file or directory
read(): [2] No such file or directory
```
I am emailing you two lines of the log and an example file.

**Comment by simon987** [comment]
I'm not able to reproduce the error at all on linux (ext4). Can you try to use the `iocharset=utf8` option when creating the docker volume? @dpieski

**Comment by dpieski** [comment]
Wow, I apologize. I completely forgot to respond here. Yes, setting `iocharset=utf8` when creating the docker volume fixed the issues with those characters. 

For reference, this is how I setup the docker volume `mydockervolume` on Windows 10 to point to a network share so I could use SIST2 on it:
```Powershell
docker volume create --driver local --opt type=cifs --opt device=//IP-ADDR/folders/ --opt o=user=MYUSERNAME,domain=MYDOMAIN,password=MYPASS,iocharset=utf8 mydockervolume
```

As far as I can tell, this issue can be closed.
