### ISSUE TITLE
Receiving exec format error on macOS

### ISSUE THREAD

**Issue by awsp** [simon987/sist2#115]
sist2 version: 2.8.4, 2.8.0

Platform (Linux or Docker, x86-64 or arm64): 
macOS 10.15.5

Elasticsearch version:
7.5.2 (launched in Docker 9200:9200)

Command with arguments:  `ex: "scan ~/Documents -o ./i2 --threads 3 -q 1.0`
```
./sist2
```
What is the expected/correct file permission to set to be? 
It complains about permission denied when extracted. I tried to set to 0644 but not success.
I had to change it to 0755 and the permission error disappeared. 

But now it shows exec format error
![image](https://user-images.githubusercontent.com/2015218/95029327-3b810080-065c-11eb-8ca1-ca2c789f327e.png)

**Comment by simon987** [comment]
Hi, sist2 has no MacOS builds (yet), sorry. (I don't have a Mac machine I can use to test/develop on)

The builds in the release page only work for linux amd64 or linux arm64

If you want to use sist2 on Mac you will need to use Docker for now

**Comment by awsp** [comment]
Got it. I will use the docker version instead. Thanks!

**Comment by cmal** [comment]
It seems in docker container, cannot acess localhost:9200 for elasticsearch.

**Comment by dpieski** [comment]
@cmal Can you post your `docker-compose` file or your docker commands for starting the elasticsearch container and your sist2 container?
