### ISSUE TITLE
Load ES mappings from external file

### ISSUE THREAD

**Issue by acc557** [simon987/sist2#117]
sist2 version: 4b4ab12fac471cc0c6bf85d5f5515eebad19587f

Platform (Linux or Docker, x86-64 or arm64):  x86-64 

Elasticsearch version: 6

Mappings are hard coded in https://github.com/simon987/sist2/blob/master/src/index/static_generated.c
It's hard to customize the tokenizer for languages other than English, especially CJK languages.

I think [fscrawler does this in a better way](https://fscrawler.readthedocs.io/en/latest/admin/fs/elasticsearch.html#mappings) by first writing out the default Elasticsearch  mapping and configurations, and users can perform updates on these file before sending them to Elasticsearch during the actual initialization.

**Comment by simon987** [comment]
Thanks for the idea, I'll implement this whenever overwriting [settings.json](https://github.com/simon987/sist2/blob/master/schema/settings.json) and [mappings.json](https://github.com/simon987/sist2/blob/master/schema/mappings.json) from file in the next release

**Comment by simon987** [comment]
Implemented in the `dev` branch, will be released in v2.8.5 shortly
