### ISSUE TITLE
Right bracket in filename is duplicated in elasticsearch

### ISSUE THREAD

**Issue by germainm** [simon987/sist2#119]
sist2 version: 2.8.4

Platform (Linux or Docker, x86-64 or arm64): x86-64

Elasticsearch version: 7.5.1

Command with arguments:  ` scan ~/Documents -o ./i2 `

to reproduce bug, create a file like `test[web].txt` in the directory to index.

text[web]].txt  will appear in elasticsearch instead text[web].txt

bug doesn't affect left bracket [  (file like "text[web[.txt"  is inserted correctly in es)

**Comment by germainm** [comment]
I disabled the function that encode  ] with a second ] in read_index_bin (and disabled the strunescape javascript function too) and it works fine now.

Not sure why you need to encoding string that way ?

**Comment by simon987** [comment]
Hi,
This is normal, file names & file paths are encoded this way to handle non-utf8 characters in file names. The file names should display correctly in the web interface

**Comment by germainm** [comment]
how do you call this encoding ?

**Comment by simon987** [comment]
There is no specific name for it
