### ISSUE TITLE
Issue loading web component

### ISSUE THREAD

**Issue by dpieski** [simon987/sist2#12]
So, trying `docker run --rm --network host --name sist2 -v $PWD/out/my_idx1:/idx -v my_vol:/files simon987/sist2 web --bind 0.0.0.0 /idx`
just sits there - there is no feedback on the screen and if I go to localhost:4090 it will not load.

If try `docker run --rm --network host --name sist2 -v $PWD/out/my_idx1:/idx -v my_vol:/files simon987/sist2 web --bind 0.0.0.0:80 /idx` (put the port on the end of the IP so that it breaks, I get this response:

[12A70A00] [2019-12-18 23:54:51] [ERROR listen_point.c:200] Error getting local address and port: Invalid argument.
[12A70A00] [2019-12-18 23:54:51] [ERROR onion.c:470] There are no available listen points
Loaded index: my_idx1
Starting web server @ http://0.0.0.0:80:4090

Then it ends the container and closes.

And lastly, if I try: 
`docker run --rm --name sist2 -a STDOUT -p 8585:8585 -v $PWD/out/my_idx1:/idx -v my_vol:/files simon987/sist2 web --bind 0.0.0.0 --port 8585 /idx`

The screen will not provide any feedback, but going to localhost:8585 will load a webpage, but the page will not search.

**Comment by simon987** [comment]
Hi, when using docker you have to make sure to specify the elasticsearch url with `--es-url`
If you started elasticsearch with docker you will need to find its IP with `docker inspect`. If you're running elasticsearch on the host you will probably need to use `--network host` docker option

**Comment by dpieski** [comment]
and the --es-url needs the port on the end, it doesn't assume the default elasticsearch port

Thanks for your help! I have it up and running now and I am playing around with it. You have done a fantastic job!
