### ISSUE TITLE
Compile non debug version

### ISSUE THREAD

**Issue by germainm** [simon987/sist2#121]
sist2 version: sist2.8.4

Platform (Linux or Docker, x86-64 or arm64):x86-64

Elasticsearch version:7.5.1

Command with arguments:  make

how can I compile the non debug version of sist2 ?

I only get sist2_debug after running make

Probably stupid question but I couldn't find

Thanks!

**Comment by simon987** [comment]
Hi,
this is not a stupid question, to compile the release version you must run cmake with `cmake -DSIST_DEBUG=off ...`. To make sure that the cmake files are updated you can run `rm -rf CMakeFiles CMakeCache.txt` before that command
