### ISSUE TITLE
Load img/sprite-skin-flat.png from relative path

### ISSUE THREAD

**Issue by acc557** [simon987/sist2#122]
sist2 version: master

Platform (Linux or Docker, x86-64 or arm64): x86-64 

Elasticsearch version:unrelated

Command with arguments:  `sist2 web`

I am trying to serve sist2 on a subdir of domain.com, everything seems to work fine, except that sist2 web ui loads `http://domain.com/img/sprite-skin-flat.png`, instead of `http://domain.com/subdir/img/sprite-skin-flat.png`  like the reset of the web resources.

Maybe there is a absolute path  in one of the css file?

**Comment by simon987** [comment]
Should be fixed in `dev` branch (will be released in v2.8.6 whenever I get the chance), please let me know if that fixed it

**Comment by acc557** [comment]
Great. It seems to work now. 

Could you also upload the source for the minimized resource files? That should make it easier to debug similar problems.

**Comment by simon987** [comment]
This specific part of the code was salvaged from a school project I did 2-3 years ago so I'm afraid that I lost the copies of the original .min.* files (and some of those have been modified directly :/) sorry
