### ISSUE TITLE
.doc support via antiword

### ISSUE THREAD

**Issue by acc557** [simon987/sist2#123]
sist2 version: master

Platform (Linux or Docker, x86-64 or arm64):x86-64

Elasticsearch version: unrelated

It would be very nice if sist2 could support the legacy .doc file. 
There are some tools or library around, like 
https://packages.debian.org/sid/antiword

**Comment by simon987** [comment]
Thanks for the suggestion .Do you happen to have a good number of .doc files you could (privately) share with me by email? It would help me a lot.

**Comment by acc557** [comment]
I have many .doc files but they are spread in multiple folders. 

I would suggest to use public ones for testing and also displaying on the demo

https://www.google.com/search?q=international+utf-8+filetype:doc

**Comment by acc557** [comment]
@simon987  Is the dev branch ready to use now?

**Comment by simon987** [comment]
Hi, it technically works but there are a lot of bug fixes pending, I have not had much time to work on this in the last few weeks.
You probably can test the dev branch right now, assuming that none of your .doc files are malformed it should work as expected

**Comment by simon987** [comment]
The .doc feature is currently available in the `dev` branch and will be released in v2.9.0

**Comment by acc557** [comment]
Antiword seems to work and generate thumb images, but it doesn't seem to convert the content .doc into UTF-8 which is required by Elasticsearch. Can it be run with `antiword -m UTF-8` ?

https://www.freebsd.org/cgi/man.cgi?query=antiword&apropos=0&sektion=0&manpath=FreeBSD+6.3-RELEASE+and+Ports&format=html
