### ISSUE TITLE
Feature request: export thumbnails database for third-party apps

### ISSUE THREAD

**Issue by simon987** [simon987/sist2#127]
The thumbnails in the lmdb created by sist2 can be beneficial for many other programs like https://github.com/filebrowser/filebrowser, but right now it's a bit complicated to get the uuid as it requires elasticsearch.

Creating a lmdb file for mapping the file path to uuids would make this possible, and I am willing to make a fork of filebrowser for sist2. :)

/cc @acc557

**Comment by simon987** [comment]
I could write a python scripts that converts the UUID->image database to filePath->image but I'm not really willing to integrate that feature directly in sist2

**Comment by acc557** [comment]
I am also writing a python script to generate a filePath->UUID database from the index file, but it has to read the full file every time which doesn't work very well on large folders.  Maybe I would use the index on elasticsearch in the end.

Is there any reason why UUID->image is preferred compared to filePath->image ?

**Comment by simon987** [comment]
The binary index format is not stable and should not be read by third-party apps. 

You can generate the json index with `sist2 index --print > index.ndjson`. It should be reasonably fast to read the whole index in python to load a UUID->filepath dict. If you're IO-bound you can compress with zstd and decompress in memory. Reading a 10GB+ .ndjson file in seconds with python is possible.

**Comment by acc557** [comment]
Thanks! I am now trying to spill the UUID->image database on the disk as uuid.jpg files, or maybe later as hash(filePath).jpg. This will make it easier for a third-party to read the thumbnails, and merge incremental scans would as simple  as a `mv old/* new/*` command.
Have you considered about similar ways before? Is there any potential drawback of doing so?

**Comment by simon987** [comment]
The original version of sist2 had a single folder with a .jpg per thumbnail but it was very messy (you can hit the ext4 file limit per folder quickly) and much slower, LMDB has performance benefits (both while scanning & while serving thumbnails) and generally makes it easier to move index folder around for huge folders.

**Comment by acc557** [comment]
Thanks! You have just saved my filesystem :)

But I am still thinking about hash(filePath) as keys in lmdb, have you also thought about this before?

**Comment by simon987** [comment]
If that makes your life easier I can change it to md5(filePath)

**Comment by simon987** [comment]
md5(filePath) is used instead of UUID in `dev` branch now (will be released in v2.9.0)
