### ISSUE TITLE
Issues with searching docx files

### ISSUE THREAD

**Issue by dpieski** [simon987/sist2#14]
With Mime Types: vnd.openxmlformats-officedocument.wordprocessingml.document selected as the only type and nothing in the search, all the *.docx documents are shown. 

For the first five documents, I opened the docx, copied a random word from the document, and pasted it in the search bar and received 0 results.

I have also tested with various other words that I know, due to the nature of the files, would appear numerous times, but I always return with 0 results.

**Comment by simon987** [comment]
Sorry there must have been a copy-paste error while reformatting the [format support](https://github.com/simon987/sist2#format-support) table, docx is not yet supported

**Comment by dpieski** [comment]
aw dang. :/ 
What would you need to support it?

**Comment by dpieski** [comment]
I seem to be having a similar issue with some doc files. It will return the search term if it is in the title but will not if it is in the document.

**Comment by simon987** [comment]
I'd need to find a library with C bindings that lets me read .docx files.
Otherwise I think I'd need to extract the file and manually read its contents but I haven't looked into it at all yet.

**Comment by dpieski** [comment]
While it appears to be dead, I think this may work / be a strong foundation for the docx/xlsx/pptx etc. files.

https://github.com/freuter/libopc
Codeplex: https://archive.codeplex.com/?p=libopc

It uses libxml and zlib as dependencies.

**Comment by dpieski** [comment]
A living xlsx library: https://github.com/brechtsanders/xlsxio

**Comment by dpieski** [comment]
I noticed I can get most of the text information from a doc file from just opening it as a text file (like in Notepad++).

I did have one issue doing that based on extensions though. I don't know if it's normal or I just picked an abnormal file to test - I have a doc file that is zipped like a docx file. So to see the info in it, I had to unzip it first.

**Comment by dpieski** [comment]
For reference if needed - The Specifications for doc/docx etc are listed here: https://docs.microsoft.com/en-us/openspecs/office_file_formats/MS-OFFFFLP/8aea05e3-8c1e-4a9a-9614-31f71e679456

The zip file "Office File Formats PDF .zip" has PDFs of MS-DOC/PPT/XLS explaining the formats. Hundreds of pages long each though.

**Comment by simon987** [comment]
@dpieski The v1.1.11 release should index docx, xlsl and pptx file contents, let me know if you get it working

**Comment by dpieski** [comment]
@simon987 Could I do --incremental or do I need to do a full scan?

**Comment by simon987** [comment]
full scan

**Comment by dpieski** [comment]
negatory.
abends with:
sist2: ../../../opc/zip.c:1009: opcZipGC: Assertion `header_size<=segment->header_size' failed.

**Comment by simon987** [comment]
I'm uploading v1.1.13, @dpieski please let me know if it fixed the issue (if not, please run with `--verbose`) and send the log
thank you!

**Comment by dpieski** [comment]
woot! It seems to be working. Tested by opening a few docs for random words to search for and I was given the document back for the search.

During the scan, I had 4 documents with the error: "Part /word/document.xml does not exist.!"
I am guessing that is what killed it last time?
