### ISSUE TITLE
Archive password support

### ISSUE THREAD

**Issue by vercas** [simon987/sist2#143]
A really nice feature to have would be a way to specify archive passwords when scanning, and have them stored in indexes so the contents of password-protected archives can be viewed in the web UI.

**Comment by simon987** [comment]
Unless I don't understand the suggestion correctly, the password does not need to be stored because the web UI never needs to read the archive file. But I can implement the feature to read protected archive files with an `--archive-password` argument

**Comment by vercas** [comment]
Well, the web UI supports listing files inside archives, and previewing them, right? e.g. playing videos?  
Or is that just for plain files?  
(I haven't gotten to the web UI yet, took me a whole day just to index my filesystem)

**Comment by simon987** [comment]
The web UI will display thumbnails etc without needing access to the original files. You can view the original file (e.g. full-size image or play video) only for files outside archives

**Comment by vercas** [comment]
Oh, I see.

**Comment by simon987** [comment]
Implemented in `dev` branch with the `--archive-passphrase`, will be available in the 2.9.1 release
