### ISSUE TITLE
Playing mp3 won't stop currently playing song

### ISSUE THREAD

**Issue by germainm** [simon987/sist2#148]
sist2 version: 2.8

Platform (Linux or Docker, x86-64 or arm64):x86-64

Elasticsearch version: opendistro

Command with arguments:  `ex: "scan ~/Documents -o ./i2 --threads 3 -q 1.0`

playing a mp3 from the web interface doesn't stop previously started song. sound is mixed together. it is sometimes not easy to find again which song is playing when there's a lot.

**Comment by simon987** [comment]
Implemented in `dev` branch, will be available in v2.9.1
