### ISSUE TITLE
Update issue templates

### ISSUE THREAD

**Issue by simon987** [simon987/sist2#151]
Setup templates for
- FR
- Bug report

**Comment by dpieski** [comment]
I created a Bug Report template, a Feature Request Template, a Documentation link to the USAGE page, and limited opening "Blank Issues". 
Hopefully that helps a little. 

I was wondering if you would want to have a separate "Feature Request" template for requests for new file types? Wasn't sure if you would want to separate those out from normal feature requests or not.
