### ISSUE TITLE
Possible Optimization in scanning with excluded directories

### ISSUE THREAD

**Issue by dpieski** [simon987/sist2#174]
sist2 version: 2.10.3

Platform (Linux or Docker, x86-64 or arm64): Ubuntu

Command with arguments:
` sudo ./sist2_2.10.3 scan --very-verbose --size=-1 --threads 8 --content-size 131072 -e "(.*\~.*)|(/Firm/Employees)" --name firm /mnt/mdrive/Firm -o /out/firm_2021.08.12`

Comments:
I am excluding the "Employees" folder. So the path would be `/mnt/mdrive/Firm/Employees/*`

The scan module is correctly excluding all files and folders under that path. 

`walk.c` still walks through all the files in that directory though. 
I was wondering if there was a possible optimization you could do where the `walk.c` module doesn't have to walk through all files in a directory if the directory is excluded.

**Comment by simon987** [comment]
Fixed in be8eedc9c7c3ce24000f69c7d6d969ee2477d599, will be released in v2.11.4
