### ISSUE TITLE
Feature request web: preview source document

### ISSUE THREAD

**Issue by vorpalhex** [simon987/sist2#19]
When doing a search and getting results, it'd be nice to preview the entire source document inline, or at least the entirety of the raw text. 

From poking around, it looks like this would need to make a request to ES to get back the entire source document based on ID, and then we'll need the UI elements to display the result.

**Comment by simon987** [comment]
What types of document do you have in mind?

> From poking around, it looks like this would need to make a request to ES to get back the entire source document based on ID, and then we'll need the UI elements to display the result.

That is correct, however, the text stored in ES is broken up (whitespace is compressed to only spaces, and special ascii characters are mostly ignored)

I'll try to see what I can do, thank you for the suggestion

**Comment by vorpalhex** [comment]
Thank you! This looks great, will give it a spin in a moment.
