### ISSUE TITLE
Sort alphabetically

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [simon987/sist2#207]
**Which SIST2 component is your Feature Request related to?**
- Web

**Is your feature request related to a problem? Please describe.**
- No

**What would you like to see happen?**
- Add alphabetical sort option

**Comment by simon987** [comment]
Implemented in ed8b4f4, will be released in v2.11.4 *You will need to re-index with the `-f` option to enable that feature.

**Comment by AbdulrhmnGhanem** [comment]
Great, thanks!
