### ISSUE TITLE
Small issue - Install?

### ISSUE THREAD

**Issue by willwade** [simon987/sist2#211]
sist2 version: 2.11.5

Platform (Linux or Docker, x86-64 or arm64):Linux-x64

Elasticsearch version:7.14.0

Command with arguments:  `ex: "scan ~/Documents -o ./i2 --threads 3 -q 1.0`

Not really an issue - just a stupid question. On linux - the release. Do you install it? Do you chmod 644 and run it?! Not clear in the docs..

**Comment by willwade** [comment]
Idiot. Curl -LO release.. 

chmod u+x release... 

Could do with being in the readme for idiots like me

**Comment by simon987** [comment]
I'll try to make it clearer in the docs
