### ISSUE TITLE
Summary of results

### ISSUE THREAD

**Issue by willwade** [simon987/sist2#213]
**Which SIST2 component is your Feature Request related to?**
Web

**Is your feature request related to a problem? Please describe.**
It can be hard to say to someone "There are n documents with this search term in, x documents with it more than a times, etc.." it would be nice to somehow have some summary data detailing the results.. 

**What would you like to see happen?**
So you do a search. Would be nice to have some basic stats on the search. 200 hits, 100 unique documents.  Maybe break it down further  50 pdfs, 20 images, etc..  I'd like to go further and export as a csv - but I realise thats probably better done directly as a ES search term. Just ES isn't the most user friendly...

**Comment by dpieski** [comment]
Clicking "Details" will give you the number of hits, query time, and combined size of the hit files. 
Maybe if the "Media types" count were updated when a search is performed, you will have your breakdown by file-type.

![image](https://user-images.githubusercontent.com/3300522/146265077-d0ff4362-ba7a-477f-86a2-1c256608258b.png)

A button to export results to CSV would be kinda cool. Maybe columns like: "File Name | Directory | Blurb with the term"

**Comment by simon987** [comment]
Is the number of hits really an important part of this feature for you? I can make the media types pane update depending on the current search and add a breakdown of the file types but total number of hits across a given document will have a significant performance impact.

**Comment by willwade** [comment]
Your solution would suffice for now !

**Comment by simon987** [comment]
Implemented in 625f3d0d6e8aff90407074a5e2ed237829d0a0aa, will be released in v2.11.6
