### ISSUE TITLE
OCR to scan images

### ISSUE THREAD

**Issue by willwade** [simon987/sist2#217]
**Which SIST2 component is your Feature Request related to?**
Scan

**Is your feature request related to a problem? Please describe.**
So OCR currently works pdf and ePub. Love it to work on images too

**What would you like to see happen?**
--ocr to work on jpeg/png etc

**Additional context**

**Comment by simon987** [comment]
Implemented in ad95684771eb92b55476f8d704df5b315fcbe77a, will be released in v2.11.6
