### ISSUE TITLE
Debug build does not work on ArchLinux

### ISSUE THREAD

**Issue by yatli** [simon987/sist2#222]
**Device Information (please complete the following information):**
 - OS: `ArchLinux`
 - Deployment: `Linux`
 - SIST2 Version: `HEAD (local docker build) and 2.11.5`

**Command with arguments** 
`sist2_debug`

**Describe the bug**
I was getting some errors during a scan and want to investigate it further. So I switched to a debug build from the release page.
Debug build does not work. `sist2_debug` wants `libasan.so.4` but ArchLinux has `libasan.so.6` -- maybe compiler/runtime library mismatch with the docker build environment.
Tried to build it in docker, same issue.

**Expected behavior**
*works*

**Actual Behavior**
`sist2: error while loading shared libraries: libasan.so.4: cannot open shared object file: No such file or directory`

**Possible workaround**
- Maybe add `-static-libasan` to debug options?

Edit: I can confirm that adding `-static-libasan` to target link options resolves the problem.
Assembly size (non-stripping): 181MB vs. 183MB

**Comment by simon987** [comment]
I think that you can get libasan4 via the `gcc9-libs` (AUR) package, or otherwise you can just copy it from the docker image.

I'll look into `-static-libasan`, if that works on my side I'll use this instead, thanks!

**Comment by cyber9723470** [comment]
Same on the official docker image. 
`apt install libasan4` end up with "Unable to locate package libasan4"

**Comment by cyber9723470** [comment]
@yatli  Could you show your build script to enable `-static-libasan`?

Mine is ``cmake -DSIST_PLATFORM=x64_linux -DSIST_DEBUG=on -DBUILD_TESTS=off  -DCMAKE_TOOLCHAIN_FILE=/vcpkg/scripts/buildsystems/vcpkg.cmake .``

**Comment by simon987** [comment]
@cyber9723470 for you you can just copy it from the sist2 image with `docker run --rm -it --entrypoint cat simon987/sist2-build '/usr/lib/x86_64-linux-gnu/libasan.so.4' > libasan.so.4` and run sist2 with `LD_LIBRARY_PATH=. sist2 ...`

**Comment by simon987** [comment]
Looks like `-static-libasan` works great, thanks for the suggestion!

Fixed in https://github.com/simon987/sist2/commit/d40f5052f986090d2f9497b0612c50c34823b10e

**Comment by cyber9723470** [comment]
Could you share a debug build? @simon987  I could try figure out why #221 happened.

**Comment by simon987** [comment]
@cyber9723470 You can download it from the development builds here: https://files.simon987.net/.gate/sist2/simon987_sist2/dev_108_d40f5052f986090d2f9497b0612c50c34823b10e/
