### ISSUE TITLE
Only read index_main.ndjson in load_incremental_index 

### ISSUE THREAD

**Issue by simon987** [simon987/sist2#225]
Only read index_main.ndjson in load_incremental_index instead of all `_index_*` files (see #224)

/cc @yatli

**Comment by simon987** [comment]
(I don't really remember if the "oroginal" index must be read or not here, but either way, there should not be a loop here, it should read the "main" and "original" indices with a hardcoded file name regardless)

**Comment by yatli** [comment]
I guess it really depends on whether the user has run index before the incremental scan. :)

**Comment by yatli** [comment]
Would you like me to give it a go?

**Comment by simon987** [comment]
> Would you like me to give it a go?

Yes you can give it a go :)
