### ISSUE TITLE
Handle multiple languages for tesseract OCR

### ISSUE THREAD

**Issue by simon987** [simon987/sist2#228]
See discussion here: https://github.com/simon987/sist2/pull/227#discussion_r780345174

The cli.c validation should handle cases where multiple languages are specified (ex. `eng+chi-sim`)

**Comment by yatli** [comment]
Report back:

Bilingual OCR works pretty well!

![image](https://user-images.githubusercontent.com/20684720/148608794-ead4023b-69ab-4014-9afc-f9807be33573.png)

![image](https://user-images.githubusercontent.com/20684720/148608773-76989a4c-7e09-4296-9ba5-942beec983e6.png)

**Comment by simon987** [comment]
Mostly implemented in https://github.com/simon987/sist2/commit/15ae2190cf36a2cfe4d33a04361b96eb3e4dd46a.

To do: add validation to make sure that all the paths are the same

**Comment by simon987** [comment]
> To do: add validation to make sure that all the paths are the same

Added validation in 64b8aab8bfa89fda6066c7d900cd264a9ac63b9d

**Comment by simon987** [comment]
Multiple languages should work in the dev branch now, note that you have to write `--ocr-lang eng+chi_sim` (not `chi-sim` with an hyphen) for it to work now

**Comment by simon987** [comment]
@yatli FYI: From experience, the language files you can find on the [tessdata-best](https://github.com/tesseract-ocr/tessdata_best) repository have much better accuracy (at the cost of slower inference time) than the one packaged by linux distributions
