### ISSUE TITLE
Return code '0' if File Not Found

### ISSUE THREAD

**Issue by dpieski** [simon987/sist2#235]
**Device Information (please complete the following information):**
 - OS: `[e.g., Ubuntu 20.04, WSL2]` Ubuntu 20.04
 - Deployment: `[Linux, Linux ARM64 or Docker]` Linux x64
 - SIST2 Version: `[e.g., v2.9.0]` 2.11.6-dbg

**Command with arguments** 

`./sist2_2.11.6-debug index --very-verbose --threads=8 --es-url=es:9200 --es-index=theindex--batch-size=2000 /foo/bar.idx`

**Describe the bug**

The file `/foo.bar.idx` does not exist. 
Sist2 returns a `File Not Found: /foo/bar.idx`
I would expect this to be a non-zero return code, however, the return code I get is `0`:
```bash
> andrew@sist2:~/search$ echo $?
> 0
```
**Expected behavior**

I would expect this to be a non-zero return code when I try to index an index that is not there.
Probably `ENOENT 2 No such file or directory`
**Screenshots**

![image](https://user-images.githubusercontent.com/3300522/149820805-07d13ea7-1047-410a-bf58-71c99494803f.png)

**Comment by dpieski** [comment]
I was looking at it more and it looks like `main.c` always returns `0`?
Is there another way to know if the sist2 command ran successfully?

**Comment by simon987** [comment]
No, the app should return `0` on successful runs and some error code otherwise, I'll try to change the error code paths and replace them with a `FATAL(...)` log message and make sure it doesn't return `0`

**Comment by simon987** [comment]
I replaced some of the error messages I found in dad14fb66dabbc1b2c606d9444e1dca736d59f3f
