### ISSUE TITLE
Demo UI selecting a media type causes an infinite loop

### ISSUE THREAD

**Issue by tkassala** [simon987/sist2#237]
**Device Information (please complete the following information):**
 - OS: `Windows 10`
 - Browsers tested on: `chrome, firefox`

**Describe the bug**
When a media type is selected, the UI and URL keep refreshing in an infinite loop.

**Steps To Reproduce**
1. Go to [the demo](https://sist2.simon987.net/)
2. Click on any of the checkboxes under "file types". Video seems to be the worst offender.

**Expected behavior**
Display the list of files without going into an infinite loop.

**Actual Behavior**
UI refreshes in an infinite loop, making it unusable.

**Screenshots**
[screen recording](https://user-images.githubusercontent.com/59953017/149832899-741369a6-7e4c-42d5-9a10-da6b73c9b39f.mp4)

**Additional context**
I don't know if this is a bug in the project itself or just in the demo since it seems like a major one that someone else would've already reported. I tested without any browser extensions enabled after the screen recording, bug persists.

**Comment by simon987** [comment]
Thanks, I had not noticed. I can reproduce on my side in Chrome but it works fine on Firefox

**Comment by dpieski** [comment]
Deselecting "Update the Media Types tree in real time" in Configuration doesn't loop.
Also loops in Edge (chrome based)
Loops on Firefox (96.0.1) for me too.

**Comment by simon987** [comment]
ok should be fixed in b799a2e976e14cbd70354ac75a693998c4b00795, will be available in the next update
