### ISSUE TITLE
Web: date picker in addition to the current sliders

### ISSUE THREAD

**Issue by yatli** [simon987/sist2#239]
Sometimes I want to look for a file that's created in a very narrow period of time, and it's difficult to adjust the range with the sliders, a few pixels off will offset date by months!

**Comment by simon987** [comment]
Implemented in cf56bdfb749eb7536b7426f93ee16fbd1afab7d9, let me know if the `zh-CN` language string I added makes sense to you (See diff [here](https://github.com/simon987/sist2/commit/cf56bdfb749eb7536b7426f93ee16fbd1afab7d9#diff-e9fd936d241c0b1182e3db599030519786a51b6a4b643389580d98388c0c92b2R397))
