### ISSUE TITLE
Additive vs. Subtractive incremental lmdb building?

### ISSUE THREAD

**Issue by yatli** [simon987/sist2#242]
When copy_table is far larger than new_table, we may as well first file copy the store and then add/remove entries from it.
The db file copy should be done before scanner kicks off, so that the parse process will write/overwrite entries.

**Comment by simon987** [comment]
Current incremental behaviour: 

1. Start with an empty store
2. During parse, only consider new/updated files and write to the store
3. for each file in the original index that was marked for copy, load from the original store and copy it to the new store (could be a little slow)

Desired behaviour:

1. Copy the entire original store (this is really fast/efficient)
2. During parse, only consider new/updated files and write (or overwrite!) to the store
3. For each file in the original index that was marked for deletion, remove from the new store

Is that correct?

One thing I'm worried about is that LMDB will not re-compact the DB, and that deleted entries will just be zeroed out without reclaiming any new space. So if there are many deleted files, the new store will not be smaller than the original store. There might be a way to ask LMDB to force de-fragmentation but I think that this is functionally equivalent to re-writing every key, which means that we're back to square one in terms of performance.

**Comment by yatli** [comment]
Yes exactly this.

FYI: https://www.openldap.org/lists/openldap-technical/201407/msg00134.html

Fragmentation is a problem for larger-than-4k entries, but fine for smaller ones (probably automatically defrag'ed)

**Comment by simon987** [comment]
Okay, got it. That's really useful information, thank you
