### ISSUE TITLE
FR: Ignore  option for folders recursively

### ISSUE THREAD

**Issue by gerroon** [simon987/sist2#26]
Hi

It would  be great if the scan has options for ignoring folders/files. I started scanning `/media` it is fine but I also have Btrfs subvolumes inside the drives, so it scans those whole drives multiple  times since they are also mounted as actual drives. I would like to be able to ignore folders with glob patters or full paths,

**Comment by simon987** [comment]
Hi, thank you for the suggestion, I'll try to get it done in the next few days.

**Comment by simon987** [comment]
Will be available in the next release

**Comment by gerroon** [comment]
So how does the exclude work? Do I provide full payhs or relative paths, or some glob pattern?

**Comment by simon987** [comment]
You can exclude files that match a regex pattern.

For example, to ignore a directory and every file in it you can use `--exclude "/my/directory/.*"`

**Comment by gerroon** [comment]
Can I use multiple --exlude flags or do I need to use command separated  list?

**Comment by gerroon** [comment]
Also is that an absolute path?

**Comment by simon987** [comment]
> Can I use multiple --exlude flags or do I need to use command separated list?

There is only one exclude flag, if you want to ignore `/mnt/videos` and `/mnt/images` for example you can use `--exclude "/mnt/(videos|images)/.*"`

> Also is that an absolute path?

The pattern is matched against the full absolute path, yes.

**Comment by gerroon** [comment]
Thankls, sounds great

**Comment by gerroon** [comment]
Btw how would I go about something like ignoring `/usr` `/var` `/media/DRIVE-A/SomeFoder`  `/media/DRIVE-B/AnotherFolder` ?

**Comment by simon987** [comment]
@gerroon I will put some examples in the documentation soon
