### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by xmlgrg** [simon987/sist2#286]
Can you make a version with GUI? We need to run on centos, because the file searcher of centos will lag

**Comment by simon987** [comment]
It does have a GUI, can you elaborate on this?

**Comment by xmlgrg** [comment]
Centos 7 KDE desktop system, similar to Dolphin file Manager  
![github](https://user-images.githubusercontent.com/26371464/163949879-8985700e-f6ed-42ae-988c-14363bc14c93.png)

**Comment by simon987** [comment]
No sorry I have no plans to implement a file browser GUI

**Comment by xmlgrg** [comment]
Thank you, too. I'll close the problem.😀



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月19日 22:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [simon987/sist2] GUI (Issue #286) |

No sorry I have no plans to implement a file browser GUI
