### ISSUE TITLE
Option to disable thumbnail creation & display

### ISSUE THREAD

**Issue by gitterspec** [simon987/sist2#289]
**Which SIST2 component is your Feature Request related to?**
Scan, Web

**Is your feature request related to a problem? Please describe.**
N/A

**What would you like to see happen?**
Option to disable thumbnails to speed up indexing and searching i.e. closer to default behavior of other traditional tools

**Comment by simon987** [comment]
Hi you can use `--thumbnail-count 0` to disable thumbnails

**Comment by gitterspec** [comment]
Thank you!
