### ISSUE TITLE
arm64 segment fault

### ISSUE THREAD

**Issue by cmal** [simon987/sist2#293]
**Device Information (please complete the following information):**
 - OS: `Ubuntu 20.04, multipass`
 - Deployment: `wget -c https://files.simon987.net/.gate/sist2/simon987_sist2/arm_master_154_25ab883063a0c6cbc9c28751adaf3979fac90f6e/sist2-arm64-linux`
 - Browser *none`
 - SIST2 Version: `see Deployment`
 - Elasticsearch Version `docker run -d -p 9200:9200 -e "discovery.type=single-node" elasticsearch:7.14.0 `

**Command with arguments** 
./sist2-arm64-linux scan epub-stock/ -o ./epub.idx

**Describe the bug**
see screenshot
**Steps To Reproduce**
in mac:
$ wget -c https://files.simon987.net/.gate/sist2/simon987_sist2/arm_master_154_25ab883063a0c6cbc9c28751adaf3979fac90f6e/sist2-arm64-linux

$ multipass exec ubuntu -- bash

in ubuntu bash:
$ chmod a+x sist2-arm64-linux
$ ./sist2-arm64-linux scan epub-stock/ -o ./epub.idx

**Expected behavior**
scan works.

**Actual Behavior**
&
**Screenshots**
![image](https://user-images.githubusercontent.com/1773318/172544825-067a62aa-fd3c-4963-ad58-3d7670947b57.png)

**Additional context**
$ uname -a
Darwin bogon 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64

$ wget -c url_to_sist2-arm64-linux

$ multipass exec ubuntu -- bash

in ubuntu bash:
$ chmod a+x sist2-arm64-linux
$ ./sist2-arm64-linux scan epub-stock/ -o ./epub.idx
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focalme[at]simon987.net. 
$ uname -a
Linux ubuntu 5.4.0-117-generic #132-Ubuntu SMP Thu Jun 2 00:40:59 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

**Comment by simon987** [comment]
Hi, can you attach this Java SE ePub file shown in the logs please?

Does it also crash when running with the --fast-epub argument?

**Comment by cmal** [comment]
Thank you for your quick reply. 
File attatched. 
[a.zip](https://github.com/simon987/sist2/files/8866147/a.zip)

It seems having the same problem when delete Java SE ePub file and using another epub file.
I will try `--fast-epub` option and comment later.

**Comment by cmal** [comment]
`--fast-epub` works well.
BTW, `sist2 web ./epub.idx` web service cannot be accessed using ip address, only `localhost`, how to fix this?
![image](https://user-images.githubusercontent.com/1773318/172749649-abf3db2f-4137-4072-b35c-adf8f4b83011.png)

**Comment by cmal** [comment]
arm64 `web` command  also got segment fault 

![image](https://user-images.githubusercontent.com/1773318/172757573-39ab5a09-f530-448e-8554-47448223479f.png)

after open the page
![image](https://user-images.githubusercontent.com/1773318/172757708-53c271f3-74bc-451a-8517-9f8a274e58b1.png)

**Comment by cmal** [comment]
==== update ====

Hi, I made another try to use docker:

`$ docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:8.2.2-arm64`


`$ docker run --platform linux/amd64 --rm -p 4090:4090 -v $(pwd):$(pwd) -w $(pwd) simon987/sist2:2.12.1-x64-linux index --force-reset --batch-size 1000 --es-url http://172.17.0.2:9200 --es-insecure-ssl epub.idx`

```
[4007D2E300] [2022-06-10 08:45:31] [ERROR web.c] CURL Error: Empty reply from server
[4007D2E300] [2022-06-10 08:45:31] [FATAL elastic.c] Could not get ES version
```


elasticsearch shows logs:
```
{"@timestamp":"2022-06-10T08:45:01.147Z", "log.level": "WARN", "message":"received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/172.17.0.2:9200, remoteAddress=/172.17.0.3:33644}", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[0a48f59626ff][transport_worker][T#4]","log.logger":"org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4HttpServerTransport","elasticsearch.cluster.uuid":"gfNW-hm6QYq2vMv1WepyYA","elasticsearch.node.id":"9O_uhi_qTsqH1ZvJoRYo9w","elasticsearch.node.name":"0a48f59626ff","elasticsearch.cluster.name":"docker-cluster"}
{"@timestamp":"2022-06-10T08:45:31.705Z", "log.level": "WARN", "message":"received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/172.17.0.2:9200, remoteAddress=/172.17.0.3:33648}", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[0a48f59626ff][transport_worker][T#5]","log.logger":"org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4HttpServerTransport","elasticsearch.cluster.uuid":"gfNW-hm6QYq2vMv1WepyYA","elasticsearch.node.id":"9O_uhi_qTsqH1ZvJoRYo9w","elasticsearch.node.name":"0a48f59626ff","elasticsearch.cluster.name":"docker-cluster"}
```

**Comment by cmal** [comment]
I will paste my commands for running sist2 using docker on Apple M1:
https://gist.github.com/cmal/99437d3b56daa0d34dd1d66ed4de1574

**Comment by simon987** [comment]
Hi if you're using docker, either

* use version 7.X
* Use https instead of http in `--es-url`
