### ISSUE TITLE
v2.12.1 Release Binaries

### ISSUE THREAD

**Issue by dpieski** [simon987/sist2#295]
sist2 version: 2.12.1

Platform (Linux or Docker, x86-64 or arm64): Linux 

The pre-compiled binaries for v2.12.1 are not in the Assets for the Release.
Were the binaries for v2.12.1 intentionally omitted from the Assets of the release?

**Comment by simon987** [comment]
Sorry I think my CI server broke when this version was released. I included the binaries for the latest version (3.0.6) which you should use over 2..12.1 now
