### ISSUE TITLE
usage in Docker

### ISSUE THREAD

**Issue by Badlee2020** [simon987/sist2#297]
hi, I have been attempting to get sist2 to run on docker, but so far no luck. the elastic search runs but the sist2 container stops and in the logs is just the usage text. 

Could you assist in getting it to run?

my docker-compose.yml
version: '3.3'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
        environment:
          - discovery.type=single-node
          - "ES_JAVA_OPTS=-Xms1G -Xmx2G"
        ports:
          - 9200:9200
          
    sist2:
        image: simon987/sist2:2.12.1-x64-linux
        command: sist2 scan /share
        volumes:
          - /volume/location:/share/location
        ports:
          - 1300:80

**Comment by Badlee2020** [comment]
figured it out

**Comment by kylemd** [comment]
> figured it out

Can you elaborate on what you did to get it to work?

**Comment by Badlee2020** [comment]
Hi kylemd,
If i remember correctly, the usage is how I had it, but without sist2 (the image is created with /root/sist2 as the mountpoint that is already the program) you just need to pass the arguments to it. I don't know if i needed to add "bash - c" before it. 

So the command is either:
"scan /share" or "bash -c scan /share"

You also need to have multiple containers run one for scan, index, web (in Portainer)

In the end i built my own image (needed other languages) and commented out "ENTRYPOINT ["/root/sist2"]" 
Then made a bash script outside of the docker container similar to "contrib/systemd/sist2-update-files.sh" in the repository. 

In Portainer i added the line "command: bash -c "/script path/script.sh""
Of course after including the "script path"  as a volume.

Hope this helps!
