### ISSUE TITLE
FR: Disable highlighting in the search listing

### ISSUE THREAD

**Issue by gerroon** [simon987/sist2#30]
Hi

It woul be nice if there is way to disable highlighting in the search listing, I personally think that it mis more of a distraction then help, at least ione should be able to enable on and off via shirtcut maybe?

See the image please for how chesboard look it gives

https://i.imgur.com/GeHja5p.png

**Comment by simon987** [comment]
Hi, thanks a lot for the suggestion!

> I personally think that it is more of a distraction then help

I'm curious, what exactly do you dislike about the highlighting? Is it the color? Is there something I could do to make it less distracting other than disabling it?

I planned to create an option to disable highlighting anyway (for performance), you will be able to disable it from the web interface in a later release

**Comment by gerroon** [comment]
I feel like it is distracting and makes it harder to reading the search results. The fact that it repeats over and over in the page is overwhelming in my opinion given that the search results are already about the searched  item. I mean hl is fine if you are looking for a word in a long text, but here we already have the intended saerches.

**Comment by simon987** [comment]
Hi, 
I've changed the highlight to a much less violent color and I added an option to disable highlighting entirely in the settings menu.

Don't hesitate if you have other requests!

Thank you
