### ISSUE TITLE
Search in file name

### ISSUE THREAD

**Issue by Doc-Steve** [simon987/sist2#300]
**Which SIST2 component is your Feature Request related to?**
Scan

**Is your feature request related to a problem? Please describe.**
no

**What would you like to see happen?**
When a file name contains a search word, the document should also be in the results.

**Comment by simon987** [comment]
Searching in the file name is already supported. Can you provide an example of it not working as expected for you?

**Comment by Doc-Steve** [comment]
My fault, tested again, it works. Thank you.
