### ISSUE TITLE
Problem with ES 8.4.1

### ISSUE THREAD

**Issue by simon987** [simon987/sist2#302]
Elasticsearch version: `docker.elastic.co/elasticsearch/elasticsearch:8.4.1`

**Comment by drewbitt** [comment]
8.3.3, 8.4.0 as well and everything later. I gave up on v8 and moved to 7.17.7 where sist2 works.

**Comment by simon987** [comment]
should be fixed in [886fa72](https://github.com/simon987/sist2/commit/886fa720ecde90afcc151e7d6818c00511f94879) (v3.0.2)

cc @Seednode
