### ISSUE TITLE
removal of configuration page

### ISSUE THREAD

**Issue by ghost** [simon987/sist2#305]
**Which SIST2 component is your Feature Request related to?**
web

**Is your feature request related to a problem? Please describe.**
no

**What would you like to see happen?**
be able to remove the configuration menu for simple public access

**Additional context**
.

**Comment by simon987** [comment]
why

**Comment by Swedish-Hermit** [comment]
Debug information is not needed for certain public access and configuration page aswell just to minimize issues that can occur or support requests for stuff that is not actually broken.
