### ISSUE TITLE
Samba-compatible ES index 

### ISSUE THREAD

**Issue by ghost** [simon987/sist2#308]
**Which SIST2 component is your Feature Request related to?**
Samba supports Elasticsearch Backend for searching, but it requires a [different ES index](https://github.com/samba-team/samba/blob/master/source3/rpc_server/mdssvc/elasticsearch_mappings.json) other than the one used by sist2.  

It would be nice if the sist2 ES index can be made compatible with samba, then people can directly search sist2 index via Windows/Mac instead of using the WebUI.

**What would you like to see happen?**

https://wiki.samba.org/index.php/Spotlight_with_Elasticsearch_Backend

https://github.com/Ellerhold/fs2es-indexer

**Additional context**
https://github.com/samba-team/samba/blob/71cef2fa1ddbe05d29e7ce571a35888ef4663b22/source3/rpc_server/mdssvc/test_mdsparser_es.c#L220

**Comment by simon987** [comment]
I think that this is out of scope for sist2.

If you wish to use sist2 to index for samba, you can loop over the contents of `_index_main.ndjson.zst` and convert it to a samba-compatible format then use something like `elasticdump` to index to ES
