### ISSUE TITLE
FR: Show the file path

### ISSUE THREAD

**Issue by gerroon** [simon987/sist2#32]
Hi

I think it would be very helpful if the found path is also written below the found item, maybe with a smaller font. I like the way things are as a user at the moment however trying to figure out where things are coming from a bit of  tediious. 

Another idea could be like aanother type like mime types and instead it only shows the folder listings, thta way one can also just click on a folder and just list the found results in that folder.

thanks

**Comment by dpieski** [comment]
Would this be like it shows the location of the file in "list" view?

**Comment by gerroon** [comment]
Hi

My original thinking was that it should be shown just below each item, when the users looks at a found item, she can see where it is coming from since it is hard to figure out from a single file name and individually clicking on hundreds of items for item info is very tedious. 

Another approach would be to have a folder tree that is constructed only based on the found items, so not all the system file tree is shown, only branches that are concern to the currently listed found items.

**Comment by dpieski** [comment]
Sorry, my comment was exceedingly poorly worded. 
On the webpage, there is an option to switch from Grid to List. If you are in list view, under each result, it will print out the path to the result file. Is that what you were asking for? The path to each file?

See, for instance, #16.

**Comment by simon987** [comment]
> I think it would be very helpful if the found path is also written below the found item, maybe with a smaller font

You can see the file path on mouse hover or by switching to 'list' view. I don't plan to add the file path to the grid view as it's intended for media-heavy display and don't want to lose any screen space.

> Another approach would be to have a folder tree that is constructed only based on the found items

The goal of sist2 is not to replace your file browser. I don't plan to add a 'tree' display option. However, I do plan to improve the 'Filter path' field to enable 'graphically' filtering the path.

**Comment by gerroon** [comment]
Hi

Yeah that would be nice to have tha tin the grid view too.

Btw howa re the results pulled? I was just looking at the search result paths and they seem a bit of random? It is definetely not based on path. I cant judge the sorting since I do not see the dates info.

It would be nice if one could sort based on date, path, name etc

thanks

**Comment by dpieski** [comment]
I second that a date filter would be useful.

**Comment by simon987** [comment]
> Yeah that would be nice to have tha tin the grid view too.

I will not add the file path in the grid view for the reasons stated above

> Btw howa re the results pulled?

Results are sorted by relevance 

> date filter

This is an entirely different topic, please open another issue for this

**Comment by gerroon** [comment]
>Results are sorted by relevance 

Well in the context of a simple file name based search, how does Sist2 determine relevance given that I am using --fast option?

**Comment by dpieski** [comment]
I may be wrong, but I am fairly sure SIST2 doesn't determine relevance, but ElasticSearch does. ElasticSearch has a _score and _tie value for the results of a query and SIST2 requests the results with _score descending, _tie ascending. 

You would have to lookup how ElasticSearch scores documents to figure out how the relevance is determined. 

You can use `sist2 index --print ./my_index/ > my_index.ndjson` from [https://github.com/simon987/sist2/blob/master/USAGE.md#index-examples](the Sist2 docs) to see what would be sent to ElasticSearch.

**Comment by simon987** [comment]
file tree in 149de95d8893e12e4130a846224832c894aa469e will be released in `v1.3.0`
