### ISSUE TITLE
Feature request to web interface

### ISSUE THREAD

**Issue by Swedish-Hermit** [simon987/sist2#322]
Which SIST2 component is your Feature Request related to?
Web interface

Is your feature request related to a problem? Please describe.
Yes. Displaying this information in a production environment releases information to the public which could lead to security and integrity issues.

What would you like to see happen?
Be able to build and contain a sist2 binary which doesn't display the "Debug information" at the bottom of the Configuration tab on the web interface. This could be implemented as a flag that can be designated at buildtime or as a toggle within a config file or similar after the build has taken place (with permissions restricted to the host).

Additional context
n/a

**Comment by simon987** [comment]
fixed in d43aac735fe664a4bc404f6800c42ccc2a0357b0
