### ISSUE TITLE
Incremental scan issues / questions

### ISSUE THREAD

**Issue by dpieski** [simon987/sist2#33]
I pulled the latest image (1.2.17)

I ran this: `docker run -it --name sist-scan-03.02 -v general:/files -v sist2_out:/out simon987/sist2 scan --verbose --incremental=/out/general_idx2 -t 2 --content-size=65536 --rewrite-url='\\[server-IP]\general\' /files -o /out/general_idx_2020.03.02`

The log starts with:
```
[32m[FDB950C0][01;34m [2020-03-02 23:50:58] [INFO main.c] sist2 v1.2.17[0m

[32m[FDB950C0][01;34m [2020-03-02 23:59:37] [INFO tpool.c] Starting thread pool with 2 threads[0m
Loaded 2050660 items in to mtime table.
```

It ended without comment. 

I ran it again with --very-verbose. The log starts with:
```
[BC6950C0] [2020-03-03 00:52:25] [DEBUG cli.c] arg quality=5.000000
[BC6950C0] [2020-03-03 00:52:25] [DEBUG cli.c] arg size=500
[BC6950C0] [2020-03-03 00:52:25] [DEBUG cli.c] arg content_size=65536
[BC6950C0] [2020-03-03 00:52:25] [DEBUG cli.c] arg threads=2
[BC6950C0] [2020-03-03 00:52:25] [DEBUG cli.c] arg incremental=/out/general_idx2
[BC6950C0] [2020-03-03 00:52:25] [DEBUG cli.c] arg output=/out/general_idx_2020.03.02/
[BC6950C0] [2020-03-03 00:52:25] [DEBUG cli.c] arg rewrite_url=\\[server-IP]\general\
[BC6950C0] [2020-03-03 00:52:25] [DEBUG cli.c] arg name=general_idx_2020.03.02
[BC6950C0] [2020-03-03 00:52:25] [DEBUG cli.c] arg depth=2147483647
[BC6950C0] [2020-03-03 00:52:25] [DEBUG cli.c] arg path=/files/
[BC6950C0] [2020-03-03 00:52:25] [DEBUG cli.c] arg archive=(null)
[BC6950C0] [2020-03-03 00:52:25] [DEBUG cli.c] arg tesseract_lang=(null)
[BC6950C0] [2020-03-03 00:52:25] [DEBUG cli.c] arg tesseract_path=(null)
[BC6950C0] [2020-03-03 00:52:25] [DEBUG cli.c] arg exclude=(null)
[BC6950C0] [2020-03-03 00:52:25] [DEBUG cli.c] arg fast=0
```
and ends with the error: `Error while opening store: No such file or directory (/out/general_idx2thumbs)`

I saw that there was no slash between idx and the thumbs folder. So I tried running again and changing the  incremental line to include a slash: `incremental=/out/general_idx2/`
Similar starting point, but ended up failing early with the error `double free or corruption (out)`

Additional question(s):
- Do you have to run incremental with the same settings as the original scan? To wit, did it fail because the first time I did not make thumbnails but this time, with incremental. I asked it to make thumbnails for changed/new files?

**Comment by simon987** [comment]
Thanks, I'll try to reproduce the problem and come up with a fix

> Do you have to run incremental with the same settings as the original scan?

No, it should work fine if the indices are both the same version.

**Comment by dpieski** [comment]
>  if the indices are both the same version.

So you mean that the initial scan and the incremental scan have to be run with the same version of sist2?

**Comment by simon987** [comment]
> initial scan and the incremental scan have to be run with the same version of sist2?

Yes, indices are not backward (or forward) compatible. The `--incremental` option should stop and print an error message if the versions are not compatible (I don't remember if it currently does that - if not, this is a feature I have to implement)

**Comment by dpieski** [comment]
Ah, then that's whats up. 
The original index is 1.2.9 and the incremental is 1.2.17.

As far as I can see from the logs, I am not getting an incompatibility error.

**Comment by simon987** [comment]
I put a safeguard against version mismatch

@dpieski  Let me know if you still have these problems even when the version is the same, I'll close this for now
