### ISSUE TITLE
Display error message in UI when Elasticsearch index does not exist yet

### ISSUE THREAD

**Issue by jimtalksdata** [simon987/sist2#331]
Hi, the demo site [shows](https://sist2.simon987.net/#/) this when clicking "Configuration" then clicking back to the home page. The search box otherwise hangs (infinitely loading progress bar). I have this same behavior (unable to search anything) on my system. No errors in docker logs.

Elasticsearch connection error
×
sist2 web module encountered an error while connecting to Elasticsearch. See server logs for more information.

**Comment by jimtalksdata** [comment]
Running on elasticsearch:7.14.0 with the newest docker image for sist2 (yesterday).

**Comment by jimtalksdata** [comment]
Hm, seems to have started working again on my end.

Does the page appear to hang when the elastic index has no content? Had to reset the container after a scan hung due to out of memory, and the page was like that until reindexing completed.

**Comment by simon987** [comment]
I fixed the demo page - sometimes it just randomly crashes or doesn't survive reboots.

> Does the page appear to hang when the elastic index has no content?

If the `sist2` elasticsearch index doesn't exist then it will break the web app and load forever like you described. I can add a message for this
