### ISSUE TITLE
Crash Recovery: Gracefully close zstd writer in signal handler

### ISSUE THREAD

**Issue by Firebug24k** [simon987/sist2#334]
**Device Information (please complete the following information):**
 - OS: Debian Bullseye
 - Deployment: Linux Docker
 - SIST2 Version: 2.12.0
 - Elasticsearch Version *(if relevant)* : 7.14.0

Command:
~/sist2 index --batch-size 1000 --es-url http://localhost:9200 /buffer/idx

I've been trying to index a few hundred TB of files, and sometimes I have garbage in the metadata that crashes the scanner (different problem, not what this report is about).  I understand that's probably impossible to narrow down, but I was hoping that when I identify the bad file, I can delete it and have the indexer continue with an incremental scan. 

When I run the above command on a crashed index (in this case, failed after about 30 hours at around 80%), it reports:

[7F816F2DAA40] [2023-01-30 12:03:25] [FATAL serialize.c] EOF before end of stream: 3

Interestingly, it successfully imports the index into elasticsearch, which is great, despite the error.  However, I can't continue the scan after removing the bad file, it just crashes with the same error.

 ./sist2 scan /quad/ --incremental=/buffer/idx -o /buffer/idx2 -t 24
[FATAL serialize.c] EOF before end of stream: 3                       

Desired behavior would for incremental to actually resume the scan so I don't have to start over.

Is the index file readable in a hex editor?  I would be happy to try and delete the offending lines if it would help troubleshoot.

**Comment by simon987** [comment]
> However, I can't continue the scan after removing the bad file, it just crashes with the same error.


Hi, the index file is a .ndjson file inside a zstd container. If it crashed during `scan` and the index file is not closed properly it will cause problems (the `EOF before end of stream` error). I think you should be able to "fix" the file with something like:

```
zstd -dc _index_main.ndjson.zst  | zstd > recovered_index.zst
mv recovered_index.zst _index_main.ndjson.zst
```

After that you should be able to resume using incremental scan

> sometimes I have garbage in the metadata that crashes the scanner (different problem, not what this report is about). I understand that's probably impossible to narrow down

Did you save the `scan` logs? It should tell you which files were being scanned when the crash happened. 

You can open another issue for this. If you send me the file that causes the crash I can figure out a way to fix it in future versions

**Comment by Firebug24k** [comment]
zstd -dc _index_main.ndjson.zst  | zstd > recovered_index.zst
ndex_main.ndjson.zst : Read error (39) : premature end

Probably an expected error, it did generate a recovered file.  The recovered file is 3GB, the original was 2.5GB (got half a GB bigger, probably something with compression level).  In any case, it looks like it worked and is back to scanning!  This saves me a massive amount of time on these huge datasets that I didn't really want to break up into separate indices.

I identified and deleted both files it crashed on already, both of them were while scanning subtitles in some pretty big Japanese-language movies, my guess is it's somewhere in there with non-handled or invalid characters.  If it dies again and the file is reasonably sized I'll open a different bug report and send you a sample.  I have a different process running on a separate archive that's been going for 210 hours of CPU time so far and no crash, so it's pretty rare.

I did notice in multithread mode (I was running 24 threads) when it crashed it just listed what each thread was working on, but it didn't say which thread died.

[7F1B30629700] [2023-01-29 04:38:12] [ERROR *SIGNAL HANDLER*] =============================================


[7F1B30629700] [2023-01-29 04:38:12] [ERROR *SIGNAL HANDLER*] Uh oh! Caught fatal signal: Segmentation fault
[7F1B30629700] [2023-01-29 04:38:12] [DEBUG *SIGNAL HANDLER*] Thread [7F1B2F627700] was working on job 'filename.mp4'
(repeat 23 more times)

Luckily I was able to isolate the folder (all threads were in the same folder, then I reran scan in single thread mode to identify the particular file).  Don't know if it's possible to better narrow down which thread dies, but it would make future troubleshooting easier.  In any case, not a huge deal.

Thanks again!

**Comment by simon987** [comment]
`Read error (39) : premature end` is expected and yes, the default compression level (1) will create bigger files than sist2 does (it uses level 10)

Great, I'll try to make it so that the index is "resumable" in the event of a crash in the next versions

Don't worry about file size you should be able to upload large files to https://upload.simon987.net/ if necessary, I'd really like to fix this subtitle issue so that it doesn't happen in the future

**Comment by simon987** [comment]
This no longer applies in 3.X.X as the index format is now a sqlite database. Resuming with `--incremental` works by default and segmentation faults are "handled" by skipping the file
