### ISSUE TITLE
date and time on search results

### ISSUE THREAD

**Issue by einfachTobi** [simon987/sist2#336]
**Which SIST2 component is your Feature Request related to?**
Web

**Is your feature request related to a problem? Please describe.**
No, just convenience.

**What would you like to see happen?**
Put "last changed"/mtime on search result cards.

**Additional context**
You can select dates between which the search results must be located and set the display order. However, in the results display it is not visible which date and time (mtime? "last changed"?) a search result has. I think that these data is there anyway, it only has to be displayed. But I'm not familiar enough with vue to implement it.

**Comment by simon987** [comment]
Hi you should be able to add a custom line with the document modification time (mtime) from the configuration page with the latest docker version `simon987/sist2:x64-linux` 

Something like this:

![image](https://user-images.githubusercontent.com/7120851/219395468-0a5022e0-8cab-4496-80fa-aec92c7e3f69.png)

**Comment by einfachTobi** [comment]
`<b>{$humanDate(doc.mtime)}</b>` works like a charm. I will update german translation as I didn't see the context before.
