### ISSUE TITLE
FR: Web: Filter / Sort by date

### ISSUE THREAD

**Issue by dpieski** [simon987/sist2#34]
On the web page, it would be helpful to filter and/or sort results by date. 
The two relevant dates may be the created date and the modified date. 

I think modified date would be more useful, at least for me, and the modified date is already saved for use with -incremental.

(I am not a UX person, so what follows are some random thoughts. I really like the simplicity of your search that just works. So, these aren't necessarily "suggestions" but more "random thoughts".)

Filters may be: before, after, equal, between. Or something like gmail has.
- Possibly add new "Date" filter tab next to "Tags". Dropdown of filter options  that gives the correct number of date boxes.
- Example from gmail: 
![image](https://user-images.githubusercontent.com/3300522/75803606-54cb7280-5d44-11ea-9c7d-10bd058424bf.png)

Sorts may be: Newest to oldest, oldest to newest. 
- Maybe a toggle under the "Date" filter tab, three options, New-Old, Old-New, Off. Default: Off to keep function the same as the current functioning.

**Comment by simon987** [comment]
Added date filter in v1.3.1, will do sort in another release

**Comment by simon987** [comment]
fixed in v2.0.0
