### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by savvasdalkitsis** [simon987/sist2#340]
- OS:  `Ubuntu 22.04.1 LTS`
 - Deployment: `Docker`
 - Browser *(if relevant)*: `Firefox`
 - SIST2 Version: `2.12.1-x64-linux`
 - Elasticsearch Version *(if relevant)* : `7.14.0`

**Command with arguments** 
`web /data/scan --es-url=elasticsearch:9200 --bind 0.0.0.0:8888`

**Describe the bug**
Web UI works as expected, can perform searches on my index and find documents correctly. 
Clicking on a doc to open in a new tab returns a 404 Not Found on a url like `https://{{DOMAIN}}/f/97ca70a0b4893999ce288fbee60329f3`
Clicking the info button on a doc works fine and shows the doc preview and extracted text on a url like `https://{{DOMAIN}/#/file?byId=97ca70a0b4893999ce288fbee60329f3`

No logs on the container when this happens unfortunately

**Comment by simon987** [comment]
Hi,
Can the web container access the original files? 
The data folder has to be mounted such that the path in `/data/scan/descriptor.json` ->`root` is available for the web UI. You can edit the descriptor.json file to adjust the path if needed

**Comment by savvasdalkitsis** [comment]
well i feel silly. i hadn't mounted the documents folder correctly. my bad
