### ISSUE TITLE
Could not find tesseract language file: deu.traineddata!

### ISSUE THREAD

**Issue by Badlee2020** [simon987/sist2#352]
Hi, 
Unfortunately, I am unable to use the OCR function. It seems as if the libraries are not installed on the 3.0.4 version (docker). When initially using sist-2admin, there is only the English files available, it does not work when selected. When looking into the “/usr/share/tessdata” folder, the files are present. Just not being found somehow by sist2. Then after trying “export TESSDATA_PREFIX='/usr/share/tessdata'” I get a list of all the available languages.  Whenever I attempt to use OCR, I get the following error.

 [ADMIN ] Starting sist2 command with args ['/root/sist2', 'scan', '/NET-SERVER/Jake/', '--threads=10', '--thumbnail-quality=2', '--thumbnail-count=1', '--thumbnail-size=552', '--content-size=32768', '--output=/sist2-admin/scan-Jake-2023-04-23 22:48:44.621898.sist2', '--depth=-1', '--archive=recurse', '--mem-buffer=2000', '--incremental', '--optimize-index', '--name=Jake', '--ocr-lang=deu+eng', '--ocr-ebooks', '--ocr-images', '--treemap-threshold=0.0005', '--json-logs', '--very-verbose']
2023-04-23 22:48:44 [WARNING main.c] Could not open original index for incremental scan: /sist2-admin/scan-Jake-2023-04-23 22:48:44.621898.sist2. Will not perform incremental scan.
2023-04-23 22:48:44 [DEBUG util.c] Looking for 'deu.traineddata' in folder '/usr/share/tessdata'
2023-04-23 22:48:44 [DEBUG util.c] Looking for 'deu.traineddata' in folder '/usr/share/tesseract-ocr/4.00/tessdata'
2023-04-23 22:48:44 [DEBUG util.c] Looking for 'deu.traineddata' in folder '/root/sist2-admin'
2023-04-23 22:48:44 [FATAL cli.c] Could not find tesseract language file: deu.traineddata!
 [ADMIN ] Process returned non-zero exit code (-10)

**Comment by simon987** [comment]
Thanks, I think that when I updated the ubuntu version the tesseract paths changed.

When this build (3.0.5) is done it should work: https://ci.simon987.net/simon987/sist2/306 let me know

**Comment by Badlee2020** [comment]
Thanks, that was a slight improvement :)

It now shows the languages that can be selected. Unfortunately, it is still giving me the same error when English, or another language is selected.

**Comment by simon987** [comment]
Okay I think a util function used to return paths with a trailing `/` but doesn't anymore.

Next build https://ci.simon987.net/simon987/sist2/308 hopefully should work now

**Comment by Badlee2020** [comment]
seems to work thanks!

**Comment by Kiskadee-dev** [comment]
Same issue with the latest pre-release and 'por' language,

 [FATAL cli.c] Could not find tesseract language file: por.traineddata!

Installed tesseract-ocr-por on debian 12
