### ISSUE TITLE
Scan: Potential optimization

### ISSUE THREAD

**Issue by dpieski** [simon987/sist2#355]
**Which SIST2 component is your Feature Request related to?**

SIST2 Scan

**Is your feature request related to a problem? Please describe.**

I have a lot of zip files. I have some of those ZIP files that have a few thousand files inside, but the ZIP files have a password, so I do not want to scan the documents in the zip file. Scan works as generally expected by getting an error when trying to scan an internal file to a protected ZIP file.

**What would you like to see happen?**

It seems that if SIST2 gets an error of "Error reading archive file: Passphrase required for this entry", jump outside the ZIP file and continue scanning instead of trying to read every file in the ZIP file and getting the same "Error reading archive file: Passphrase required for this entry".

**Additional context**

Just a question, should that be an "Error" or a "Warning" if it cannot scan a file inside a ZIP file due to a Password restriction?
I do not know if there is a "standard practice" for this.

**Comment by dpieski** [comment]
Forgot to include:

SIST2 Version: 3.0.6+
Platform: Docker

**Comment by simon987** [comment]
I think "error" generally means "I cannot scan this file" and warning means "scanned results for this file could be inaccurate or incomplete" but it's a bit arbitrary right now.

Thanks for the suggestion, it's easy enough to change. I'll definitely change the behaviour

**Comment by simon987** [comment]
should be fixed in e2e0cf260fb5511063481c8d86cd9e0790d98f70
