### ISSUE TITLE
Admin: Log Management

### ISSUE THREAD

**Issue by dpieski** [simon987/sist2#358]
**Which SIST2 component is your Feature Request related to?**

Sist2-Admin

**Is your feature request related to a problem? Please describe.**

Can we add basic log management? At minimum a delete button (Maybe at the end of the row on the 'Task History' pane?

**What would you like to see happen?**

Be able to remove logs. Either a date-based removal or a manual delete.

**Additional context**

One of the scans I do generates a log file that is like 3.5 GB. After a couple weeks, that will take up a lot of space. Even if the history is kept in the database with the status of that particular scan, the log may not be necessary to keep around for long periods of time. But if the log is removed and the db entry is kept, we would need to handle no log file being available.

**Comment by simon987** [comment]
implemented in [5522bcf](https://github.com/simon987/sist2/commit/5522bcfa9bc3d8bff82325c28a6b393554bec158)

I added both a button to delete specific log files and a parameter to keep hte last N log files (per job setting)
