### ISSUE TITLE
Admin: Job "last scan" time

### ISSUE THREAD

**Issue by dpieski** [simon987/sist2#359]
**Device Information (please complete the following information):**
 - OS: `[e.g., Ubuntu 20.04, WSL2]`
 - Deployment: `[Linux, Linux ARM64 or Docker]`
 - Browser *(if relevant)*: `[e.g., chrome, safari]`
 - SIST2 Version: `[e.g., v2.9.0]`
 - Elasticsearch Version *(if relevant)* : ``
Sist2 3.0.6+

Microsoft Edge
Version 112.0.1722.64 (Official build) (64-bit)

**Describe the bug**

![image](https://user-images.githubusercontent.com/3300522/235736763-c716c420-8d7d-49fa-bc5f-61c937afd37a.png)
 The "last scan" time is in the future. [Just after scanning, it says "in 5 hours"

**Additional context**
I think the UTC time is being displayed as the local time? 
Since I am in UTC-5, the current UTC time is 5 hours "in the future" from my actual time.

**Comment by Badlee2020** [comment]
To get the correct time for the  tasks, you just need to set the time zone in docker..
https://support.circleci.com/hc/en-us/articles/115015771347-How-do-I-set-the-timezones-in-Docker-images-

**Comment by simon987** [comment]
Should be fixed in [f0fd708](https://github.com/simon987/sist2/commit/f0fd7080822f64edf2c67d97848ab27b64289ee5); timestamps are saved in UTC regardless of the container timezone and is displayed in the browser's timezone
