### ISSUE TITLE
Possible Admin Log Optimization

### ISSUE THREAD

**Issue by dpieski** [simon987/sist2#360]
sist2 version: Docker 3.0.6+

I noticed that it would take a while when I would look at some of the log files. 

I looked into how you are doing the `def tail()` in `sist2/sist2-admin/sist2_admin/app.py`

I messed around with other ways to do `tail` (read: looked through SO to find other solutions). And I timed them.

Here is a gist with what I did: 
https://gist.github.com/dpieski/3d5142a61caa84c62974f975356551e7

There are very, very significant differences for the larger files.

**Comment by simon987** [comment]
Hi this is great but unfortunately this doesn't work for viewing logs in real-time as it updates and more lines are being appended to it
