### ISSUE TITLE
Admin: Scheduled Job not running

### ISSUE THREAD

**Issue by dpieski** [simon987/sist2#361]
**Device Information (please complete the following information):**
 - OS: `[e.g., Ubuntu 20.04, WSL2]` Ubuntu 22.04
 - Deployment: `[Linux, Linux ARM64 or Docker]` Docker
 - SIST2 Version: `[e.g., v2.9.0]` 3.0.6+

**Describe the bug**

Jobs scheduled on the Admin job page are not triggering.

**Additional context**

I think there is an error in [`sist2/sist2-admin/sist2_admin/app.py` line 141](https://github.com/simon987/sist2/blob/63027dd5ca737a2304946ee0d34d034534f690b8/sist2-admin/sist2_admin/app.py#LL141C1-L142C1)
- I think it may be silently failing here.

I commented out that line and it seems to be working for me now. I didn't send a PR because I am not sure if that line is there for some other reason / I am not sure what is being accomplished with it.

**Comment by dpieski** [comment]
Maybe those lines should be something along the lines of:
```python
def _run_job(job: Sist2Job):
    if job.status == JobStatus("created"):
        job.last_modified = datetime.now()
        job.status = JobStatus("started")
        db["jobs"][job.name] = job

    scan_task = Sist2ScanTask(...)....
```

**Comment by simon987** [comment]
Hi, are you sure that there are no errors at all in the docker logs? Is it *always* failing or only for certain jobs?

**Comment by Badlee2020** [comment]
This and https://github.com/simon987/sist2/issues/346 are related. I am trying it again with a clean setup. I have 4 tasks, and only one that should run via Cron. After the third task was created it started to not work

**Comment by simon987** [comment]
Thanks a lot for the info @dpieski, I'll follow up in #346
