### ISSUE TITLE
Segmentation fault when scanning files with the docker image with OCR enabled

### ISSUE THREAD

**Issue by lovek323** [simon987/sist2#368]
**Device Information (please complete the following information):**
 - OS: NixOS
 - Deployment: Docker
 - Browser *(if relevant)*: N/A
 - SIST2 Version: 3.1.0
 - Elasticsearch Version *(if relevant)* : 7.17.9

**Command with arguments** 
Running a job through the web interface (epub enabled, eng OCR language used)

**Describe the bug**
I receive log messages like this:

```
2023-06-02 10:31:42 [DEBUG pdf-filename.pdf] Starting parse job {2a4de4453f665517ab252b60e4e408be}
2023-06-02 10:31:44 [DEBUG tpool.c] Child process terminated with status code 0
2023-06-02 10:31:44 [FATAL tpool.c] Child process crashed (Segmentation fault).
                                         The process was working on pdf-filename.pdf
```

This seems to happen with all files (I've seen errors for JPG, PDF, and EPUB files).

**Steps To Reproduce**
1. Create a new job in the admin web interface
2. Click 'Index now'
3. Watch the log files

**Expected behavior**
There are no segmentation faults

**Actual Behavior**
There are segmentation faults

**Screenshots**
![image](https://github.com/simon987/sist2/assets/265084/76ac57bd-dc7c-489b-91da-3572b080330f)

This screenshot shows the only options (apart from the directory) that I've changed in the web UI

**Additional context**

**Comment by simon987** [comment]
@lovek323 Can you try again with the `simon987/sist2:3.1.1-x64-linux` tag?

**Comment by lovek323** [comment]
Hi. Yes, I tried the new tag, but now I get an issue with ```sist2 web module encountered an error while connecting to Elasticsearch. See server logs for more information.```

I don't see much in the logs, but I'm happy to upload them if they're useful.

**Comment by lovek323** [comment]
Looks like that Elasticsearch error was not related, but I fixed it by setting the `ingest.geoip.downloader.enabled=false` env var.

**Comment by lovek323** [comment]
Thanks, that's working now.

**Comment by lovek323** [comment]
Thanks, that's working now.
