### ISSUE TITLE
Date Picker showing malformed year

### ISSUE THREAD

**Issue by overbyrn** [simon987/sist2#376]
**Device Information (please complete the following information):**
 - OS: `[e.g., Ubuntu 20.04, WSL2]`  Debian 11
 - Deployment: `[Linux, Linux ARM64 or Docker]` Docker   ( simon987/sist2:x64-linux )
 - Browser *(if relevant)*: `[e.g., chrome, safari]`
 - SIST2 Version: `[e.g., v2.9.0]`  3.1.2
 - Elasticsearch Version *(if relevant)* : ``  7.17.9

**Describe the bug**
Date Picker showing malformed year.  This only occurs when using Elasticsearch as the backend

**Screenshots**
![fig1](https://github.com/simon987/sist2/assets/545222/958d571c-bab5-4aa5-b44a-9bd44e4295bd)

![fig2](https://github.com/simon987/sist2/assets/545222/13d75426-f910-45de-9c97-3487dcbfd19f)

**Comment by simon987** [comment]
Fixed in https://github.com/simon987/sist2/commit/5a1a04629f6b237b3d78b18f3060aef938449ab9, will be included in the next release
