### ISSUE TITLE
RuntimeError: Directory './frontend/dist' does not exist

### ISSUE THREAD

**Issue by arthuraltino** [simon987/sist2#383]
**Device Information (please complete the following information):**
 - OS: Ubuntu Server 22.04
 - Deployment: Linux ARM64
 - SIST2 Version: master branch

**Command with arguments** 
sudo docker-compose up

**Describe the bug**
When i try to build and run the Arm64 version the following error causes the container to exit:
```
sist2-admin  | Traceback (most recent call last):
sist2-admin  |   File "/root/sist2-admin/sist2_admin/app.py", line 43, in <module>
sist2-admin  |     app.mount("/ui/", StaticFiles(directory="./frontend/dist", html=True), name="static")
sist2-admin  |   File "/usr/local/lib/python3.10/dist-packages/starlette/staticfiles.py", line 57, in __init__
sist2-admin  |     raise RuntimeError(f"Directory '{directory}' does not exist")
sist2-admin  | RuntimeError: Directory './frontend/dist' does not exist
sist2-admin exited with code 1
```

**Steps To Reproduce**
1. git clone --recursive https://github.com/simon987/sist2/
2. cd sist2
3. add dockerfile: Dockerfile.arm64 to docker-compose.yml
4. docker-compose up

**Expected behavior**
Run the container.

**Actual Behavior**
The container won't start because of the error described above.

**Comment by simon987** [comment]
Thanks, I think that the NPM build step is not included in the arm64 image, I'll update it when I have a chance

**Comment by arthuraltino** [comment]
It was exactly that.
I've finally made the arm64 build run after some changes in the Dockerfile.arm64 file, the docker-compose.yml and in the sist2-admin/requirements.txt file.

**Dockerfile.arm64:**
`FROM simon987/sist2-build-arm64 as build
MAINTAINER simon987 <me@simon987.net>
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash
RUN apt update -y; apt install -y nodejs nano && rm -rf /var/lib/apt/lists/*
WORKDIR /build/
COPY scripts scripts
COPY schema schema
COPY CMakeLists.txt .
COPY third-party third-party
COPY src src
COPY sist2-vue sist2-vue
COPY sist2-admin sist2-admin
RUN cd sist2-vue/ && npm install && npm run build
RUN cd sist2-admin/frontend/ && npm install && npm run build
# ADD . /build/
RUN mkdir build && cd build && cmake -DSIST_PLATFORM=arm64_linux_docker -DSIST_DEBUG_INFO=on -DSIST_DEBUG=off -DBUILD_TESTS=off -DCMAKE_TOOLCHAIN_FILE=/vcpkg/scripts/buildsystems/vcpkg.cmake ..
RUN cd build && make -j$(nproc)
RUN strip build/sist2 || mv build/sist2_debug build/sist2

FROM --platform=linux/arm64/v8 ubuntu@sha256:537da24818633b45fcb65e5285a68c3ec1f3db25f5ae5476a7757bc8dfae92a3

WORKDIR /root

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

ENTRYPOINT ["/root/sist2"]

RUN apt update && apt install -y curl libasan5 libmagic1 tesseract-ocr python3-pip python3 git && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/share/tessdata && \
    cd /usr/share/tessdata/ && \
    curl -o /usr/share/tesseract-ocr/4.00/tessdata/hin.traineddata https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/hin.traineddata &&\
    curl -o /usr/share/tesseract-ocr/4.00/tessdata/jpn.traineddata https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/jpn.traineddata &&\
    curl -o /usr/share/tesseract-ocr/4.00/tessdata/eng.traineddata https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/eng.traineddata &&\
    curl -o /usr/share/tesseract-ocr/4.00/tessdata/fra.traineddata https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/fra.traineddata &&\
    curl -o /usr/share/tesseract-ocr/4.00/tessdata/rus.traineddata https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/rus.traineddata &&\
    curl -o /usr/share/tesseract-ocr/4.00/tessdata/osd.traineddata https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/osd.traineddata &&\
    curl -o /usr/share/tesseract-ocr/4.00/tessdata/spa.traineddata https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/spa.traineddata &&\
    curl -o /usr/share/tesseract-ocr/4.00/tessdata/deu.traineddata https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/deu.traineddata &&\
    curl -o /usr/share/tesseract-ocr/4.00/tessdata/equ.traineddata https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/equ.traineddata &&\
    curl -o /usr/share/tesseract-ocr/4.00/tessdata/por.traineddata https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/por.traineddata &&\
    curl -o /usr/share/tesseract-ocr/4.00/tessdata/chi_sim.traineddata https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/chi_sim.traineddata

# sist2
COPY --from=build /build/build/sist2 /root/sist2

# sist2-admin
COPY sist2-admin/requirements.txt sist2-admin/
RUN python3 -m pip install --no-cache -r sist2-admin/requirements.txt
COPY --from=build /build/sist2-admin/ sist2-admin/
`

**docker-compose.yml**
`version: "3"

services:
  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: sist2-es
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
  sist2-admin:
    build:
      context: .
      **dockerfile: Dockerfile.arm64**
    container_name: sist2-admin
    volumes:
      - /mnt/array/sist2-admin-data/:/sist2-admin/
      - /:/host
    ports:
      - 4090:4090
      # NOTE: Don't export this port publicly!
      - 8080:8080
    working_dir: /root/sist2-admin/
    entrypoint: python3
    command:
      - /root/sist2-admin/sist2_admin/app.py
`

sist2-admin/requirements.txt:
`fastapi
git+https://github.com/simon987/hexlib.git
uvicorn
websockets
pycron
**pydantic==1.10.11**
`

**Comment by simon987** [comment]
thanks for the updated dockerfile, this should be fixed in the latest version
