### ISSUE TITLE
Missing language select menu

### ISSUE THREAD

**Issue by rickcecil** [simon987/sist2#384]
**Device Information (please complete the following information):**
 - OS: `Ubuntu 20.04`
 - Deployment: `Docker`
 - Browser `chrome`
 - SIST2 Version: `3.1.0`
 - Elasticsearch Version *(if relevant)* : `7.17.9`

**Describe the bug**
When trying to create a second index, I do not have the option to select a language. When I select "Enable OCR'ing of image files" or "OCR'ing of ebook files" I get an error that I need to select a language, but there are no options under the label: "Tesseract language." A list of items was available there when I created the first index.

Note: Not sure if relevant, but when I created the first index, I had it only index file names and mime types so that I could get a quick scan of the directory with the intent to do a fulltext, including OCR, at a later point.

**Steps To Reproduce**
Uncertain. I can provide whatever information you need -- and can try to recreate the issue with another instance of docker if needed. 

**Expected behavior**
Display a list of language options so that I can OCR images and ebooks when I create additional indexes.

**Screenshots**

The missing options:

<img width="1036" alt="Screenshot 2023-07-12 at 6 45 42 AM" src="https://github.com/simon987/sist2/assets/715483/9dc7137f-a9bc-4ef3-a9e1-07df7b2b297d">

**Comment by rickcecil** [comment]
FWIW, I am serving this through Nginx Proxy Manager and have noticed some insecure content warnings. Upon accessing the site through the IP address, the options are available and the insecure content warnings disappear. 

Here is the warning that I am getting:

```
app.js:1 Mixed Content: The page at 'https://sist2.mydomain.com/ui/#/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://sist2.mydomain.com/notifications'. This request has been blocked; this endpoint must be available over WSS.
connectNotifications @ app.js:1
chunk-vendors.js:289 DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at o.connectNotifications (https://sist2.mydomain.com/ui/js/app.js:1:11199)
    at o.mounted (https://sist2.mydomain.com/ui/js/app.js:1:11131)
    at re (https://sist2.mydomain.com/ui/js/chunk-vendors.js:289:11710)
    at xa (https://sist2.mydomain.com/ui/js/chunk-vendors.js:289:29272)
    at Object.insert (https://sist2.mydomain.com/ui/js/chunk-vendors.js:289:20948)
    at O (https://sist2.mydomain.com/ui/js/chunk-vendors.js:289:47962)
    at Hn.__patch__ (https://sist2.mydomain.com/ui/js/chunk-vendors.js:289:49278)
    at Ya.t._update (https://sist2.mydomain.com/ui/js/chunk-vendors.js:289:27110)
    at Hn.n (https://sist2.mydomain.com/ui/js/chunk-vendors.js:289:27916)
    at nn.get (https://sist2.mydomain.com/ui/js/chunk-vendors.js:289:30811)
oe @ chunk-vendors.js:289
/ui/#/:1 Mixed Content: The page at 'https://sist2.mydomain.com/ui/#/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://sist2.mydomain.com/api'. This request has been blocked; the content must be served over HTTPS.
/ui/#/:1 Uncaught (in promise) rcode: "ERR_NETWORK"config: adapter: ƒ (t)data: undefinedenv: {FormData: null}headers: {Accept: 'application/json, text/plain, */*'}maxBodyLength: -1maxContentLength: -1method: "get"timeout: 0transformRequest: [ƒ]transformResponse: [ƒ]transitional: {silentJSONParsing: true, forcedJSONParsing: true, clarifyTimeoutError: false}url: "https://sist2.mydomain.com/api/"validateStatus: ƒ (t)xsrfCookieName: "XSRF-TOKEN"xsrfHeaderName: "X-XSRF-TOKEN"[[Prototype]]: Objectmessage: "Network Error"name: "AxiosError"request: XMLHttpRequest {data: undefined, onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, …}response: XMLHttpRequest {data: undefined, onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, …}[[Prototype]]: Error
```

Maybe I've not set up Sist2 and NPM properly? I can investigate more later.

**Comment by simon987** [comment]
> Mixed Content: The page at 'https://sist2.mydomain.com/ui/#/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://sist2.mydomain.com/api'. This request has been blocked; the content must be served over HTTPS.

This is because the `ws://` scheme is hard-coded in sist2-admin. In your case (reverse proxy w/ SSL), it should be `wss://`. I pushed a fix in the latest version (`simon987/sist2:x64-linux` image), could you try and see if that fixes the that error?

**Comment by simon987** [comment]
> do not have the option to select a language

Can you navigate to https://sist2.mydomain.com/api and send me the result? It should look like this:

```
{"tesseract_langs":["chi_sim","deu","eng","equ","fra","hin","jpn","pol","rus","spa"],"logs_folder":"/sist2-admin/logs"}
```

**Comment by rickcecil** [comment]
> > Mixed Content: The page at 'https://sist2.mydomain.com/ui/#/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://sist2.mydomain.com/api'. This request has been blocked; the content must be served over HTTPS.
> 
> This is because the `ws://` scheme is hard-coded in sist2-admin. In your case (reverse proxy w/ SSL), it should be `wss://`. I pushed a fix in the latest version (`simon987/sist2:x64-linux` image), could you try and see if that fixes the that error?

When I use that image, everything starts, but I get these errors in the sist2 admin logs:

```
TypeError: The `encoder` argument is no longer supported; use field serializers instead.
2023-07-13 03:04:47 [INFO] Migrating to v4 database schema
Traceback (most recent call last):
  File "/root/sist2-admin/sist2_admin/app.py", line 479, in <module>
    migrate_v3_to_v4(db)
  File "/root/sist2-admin/sist2_admin/state.py", line 124, in migrate_v3_to_v4
    create_default_search_backends(db)
  File "/root/sist2-admin/sist2_admin/state.py", line 116, in create_default_search_backends
    db["search_backends"]["elasticsearch"] = es_backend
  File "/usr/local/lib/python3.10/dist-packages/hexlib/db.py", line 210, in __setitem__
    self.setitem_pydantic(key, value)
  File "/usr/local/lib/python3.10/dist-packages/hexlib/db.py", line 201, in setitem_pydantic
    "json": value.json(encoder=_json_encoder, indent=2),
  File "/usr/local/lib/python3.10/dist-packages/typing_extensions.py", line 2562, in wrapper
    return __arg(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 922, in json
    raise TypeError('The `encoder` argument is no longer supported; use field serializers instead.')
```

Is there a migration I need to run?

**Comment by rickcecil** [comment]
> > do not have the option to select a language
> 
> Can you navigate to https://sist2.mydomain.com/api and send me the result? It should look like this:
> 
> ```
> {"tesseract_langs":["chi_sim","deu","eng","equ","fra","hin","jpn","pol","rus","spa"],"logs_folder":"/sist2-admin/logs"}
> ```

While I wasn't able to get to /api in the new image, I tried it in the previous image and got this response:

```
{"tesseract_langs":["chi_sim","deu","eng","equ","fra","hin","jpn","pol","rus","spa"],"logs_folder":"/sist2-admin/logs"}
```

**Comment by simon987** [comment]
>  get these errors in the sist2 admin logs

Sorry about that, a new version of a python package was released recently and broke the image, could you try again with the same tag (`docker pull simon987/sist2:x64-linux`) ?

**Comment by rickcecil** [comment]
In that most recent version, did you intend to reduce "Indexing Options" to a single field? 

<img width="742" alt="Screenshot 2023-07-13 at 10 29 09 PM" src="https://github.com/simon987/sist2/assets/715483/338103ff-1b29-4d68-959e-4740e0c8d150">

FWIW, in my setup, all of my docker containers share a network with nginx-proxy-manager and I had to change the name of sist2's elasticsearch container because it kept pinging another, older version of elasticsearch that was already at http://elasticsearch in docker. 

I would assume that I could pass options from here into that single line:

https://github.com/simon987/sist2/blob/master/docs/USAGE.md

Currently, though, that field is not selectable.

Of course, that is all assuming that you intended to hide those options.

Anyway, I am going to bring that other container down and then restart this one so I can test this new image. Will post back here shortly.

**Comment by rickcecil** [comment]
> In that most recent version, did you intend to reduce "Indexing Options" to a single field?

AH! I see now. I missed the options to enter the elasticsearch information on the first page. This is a great improvement! It was a bit annoying having to correct the elasticsearch url for each of the indexes. Very nice. 

The only thing to consider is putting an error message in the screenshot in my previous post: 
```
Cannot connect to elasticsearch. Configure elasticsearch here. 
```

Or if you need it to be more generic:

```
I cannot connect to one of your databases. Please correct the configurations. (Note: this is accessible at the bottom of the homepage/dashboard.)
```

And provide a direct link to the configuration -- or not. If you've provided instructions, it might be better to let them actually access it in the correct way.

All that being said, I may have a very unique and unusual use case, so it may not be worth the time. 

I am not off to test the original purpose of this ticket. Back shortly.

**Comment by rickcecil** [comment]
From what I can tell, I need to create the search backend/index first. Then, once I've created the search index, I can link that to a job. A single search index can be linked to multiple jobs. (Is this a good idea? I'm really not sure the implications of doing this -- I likely need to do some reading up elastic search to understand that better, but would appreciate pointers.)

Then, I also need to associate the frontend with the same index/search backend as the jobs that I have selected? What happens if I select a different index/backend? Or what happens if I select several jobs with different backends?

I could help with the UI and workflow if I can understand things a little better -- I am a UX designer and happy to help, but want to make sure I understand the relationships. As it is, at least as far as I understand things, people could get themselves into trouble pretty easily, but I am speculating based on what I see here.

Ultimately, I really like this direction. It is very clever and seemingly very flexible. All-in-all, I am very impressed with Sist2 and I haven't even gotten to test the automated tagging. Seriously looking forward to trying that out.

I am currently re-indexing my files. I didn't see any way around that given the changes to the index/backend. These are fairly large indexes. I will post back here once it has finished.

(And apologies for all the posts, but wanted to report on my experiences and I thought you might find it useful.)

**Comment by rickcecil** [comment]
After reindexing, I still don't see the options to select a language:

Screenshot:
```
<img width="742" alt="Screenshot 2023-07-13 at 11 30 26 PM" src="https://github.com/simon987/sist2/assets/715483/5f357ec3-407e-4318-a08e-bddef0ba5d60">
```

Browser logs:
```
/ui/#/job/dnd-reference:1 Mixed Content: The page at 'https://sist2.mydomain.com/ui/#/job/dnd-reference' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://sist2.mydomain.com/api'. This request has been blocked; the content must be served over HTTPS.
/ui/#/job/dnd-reference:1 Uncaught (in promise) r {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …}
Promise.then (async)
mounted @ app.js:1
re @ chunk-vendors.js:289
xa @ chunk-vendors.js:289
insert @ chunk-vendors.js:289
O @ chunk-vendors.js:289
(anonymous) @ chunk-vendors.js:289
Ya.t._update @ chunk-vendors.js:289
n @ chunk-vendors.js:289
nn.get @ chunk-vendors.js:289
nn @ chunk-vendors.js:289
Ba @ chunk-vendors.js:289
Hn.$mount @ chunk-vendors.js:289
7265 @ app.js:1
n @ app.js:1
(anonymous) @ app.js:1
n.O @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
```

/api:
```
{"tesseract_langs":["chi_sim","deu","eng","equ","fra","hin","jpn","pol","rus","spa"],"logs_folder":"/sist2-admin/logs"}
```
Let me know if you need anything else.

**Comment by simon987** [comment]
Hi, thanks so much for your thoughts on the UX, I moved your comments to a separate issue so it's easier to track for me

**Comment by simon987** [comment]
> 'http://sist2.mydomain.com/api'. This request has been blocked

I believe this is because the request is made to /api/ , and nginx likes to redirect to /api (without the forward slash). For some reason it redirects with insecure http. This can probably be fixed with the right combination of proxy_pass settings but for now I just updated the code so that it requests /api instead. Can you try with the latest version? (simon987/sist2:x64-linux again)

**Comment by rickcecil** [comment]
So, I pulled and tested, but now the dashboard has perpetual loading bars under each of the sections (search backend, jobs, frontend). Here are the errors that I am getting: 

```
/ui/#/:1 Mixed Content: The page at 'https://my.domain.com/ui/#/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://my.domain.com/api/job/'. This request has been blocked; the content must be served over HTTPS.
/ui/#/:1 Uncaught (in promise) r {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …}
Promise.then (async)
reload @ app.js:1
mounted @ app.js:1
re @ chunk-vendors.js:289
xa @ chunk-vendors.js:289
insert @ chunk-vendors.js:289
O @ chunk-vendors.js:289
(anonymous) @ chunk-vendors.js:289
Ya.t._update @ chunk-vendors.js:289
n @ chunk-vendors.js:289
nn.get @ chunk-vendors.js:289
nn @ chunk-vendors.js:289
Ba @ chunk-vendors.js:289
Hn.$mount @ chunk-vendors.js:289
7265 @ app.js:1
n @ app.js:1
(anonymous) @ app.js:1
n.O @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
/ui/#/:1 Mixed Content: The page at 'https://my.domain.com/ui/#/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://my.domain.com/api/frontend/'. This request has been blocked; the content must be served over HTTPS.
/ui/#/:1 Mixed Content: The page at 'https://my.domain.com/ui/#/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://my.domain.com/api/search_backend/'. This request has been blocked; the content must be served over HTTPS.
/ui/#/:1 Uncaught (in promise) r {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …}
Promise.then (async)
reload @ app.js:1
mounted @ app.js:1
re @ chunk-vendors.js:289
xa @ chunk-vendors.js:289
insert @ chunk-vendors.js:289
O @ chunk-vendors.js:289
(anonymous) @ chunk-vendors.js:289
Ya.t._update @ chunk-vendors.js:289
n @ chunk-vendors.js:289
nn.get @ chunk-vendors.js:289
nn @ chunk-vendors.js:289
Ba @ chunk-vendors.js:289
Hn.$mount @ chunk-vendors.js:289
7265 @ app.js:1
n @ app.js:1
(anonymous) @ app.js:1
n.O @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
/ui/#/:1 Uncaught (in promise) r {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …}
Promise.then (async)
reload @ app.js:1
mounted @ app.js:1
re @ chunk-vendors.js:289
xa @ chunk-vendors.js:289
insert @ chunk-vendors.js:289
O @ chunk-vendors.js:289
(anonymous) @ chunk-vendors.js:289
Ya.t._update @ chunk-vendors.js:289
n @ chunk-vendors.js:289
nn.get @ chunk-vendors.js:289
nn @ chunk-vendors.js:289
Ba @ chunk-vendors.js:289
Hn.$mount @ chunk-vendors.js:289
7265 @ app.js:1
n @ app.js:1
(anonymous) @ app.js:1
n.O @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
``` 

I've started poking at the proxy pass thing for nignx, but haven't hit on the right option just yet -- admittedly, I haven't spent a ton of time on it just yet, though. Mostly learning what it can do. Will let you know if I can make something work there.

**Comment by simon987** [comment]
My mistake, I updated the API endpoints to have no trailing slash for only some of the endpoints and forgot some. Can you try again with the latest version?

**Comment by rickcecil** [comment]
It works! :)
