### ISSUE TITLE
Stats page broken?

### ISSUE THREAD

**Issue by lyc8503** [simon987/sist2#387]
**Device Information (please complete the following information):**
 - OS: `Windows 10`
 - Deployment: `The official demo: https://sist2.simon987.net/`
 - Browser *(if relevant)*: `Chrome 114, Edge 114, Firefox 115`
 - SIST2 Version: `3.1.1`

**Command with arguments** 
Null

**Describe the bug**
The stats page is not showing anything on my PC.

**Steps To Reproduce**
Please be specific!
1. Use chrome to open https://sist2.simon987.net/
2. Click on `Stats`
3. Nothing shows up
![image](https://github.com/simon987/sist2/assets/36782264/d942bb65-a8d3-4822-b73b-48c3ae74211c)

**Expected behavior**
The stats page shows correctly.

**Actual Behavior**
Just see a blank page.

**Screenshots**
![image](https://github.com/simon987/sist2/assets/36782264/d672eeac-590b-497e-a89a-b830d57df221)

The only error showing up in the console is
![image](https://github.com/simon987/sist2/assets/36782264/55e71cde-f4ce-421b-beeb-d9fb0548e833)

**Comment by simon987** [comment]
Thanks, should be fixed in 0b0b7fe
