### ISSUE TITLE
After I restart docker, the frontend is unable to connect to Elasticsearch

### ISSUE THREAD

**Issue by rickcecil** [simon987/sist2#398]
**Device Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Deployment: Docker
 - SIST2 Version: 3.2
 - Elasticsearch Version *(if relevant)* : 7.17.9

**Describe the bug**
When I bring Sist2 back up (docker-compose up -d) after having shut down docker (docker-compose down), I get the following error when I go to a frontend: 

```
sist2 web module encountered an error while connecting to Elasticsearch. See server logs for more information.
```

I do not see any errors in the server logs (either admin or elasticsearch)-- at least, not in what is getting spit out through Docker. I have not looked inside the docker container at any other logs that might exist.

**Steps To Reproduce**
Please be specific!
1. Bring Sist2 up using "docker-compose up -d"
2. Run a job
3. Create and start a frontend
4. Make sure frontend is working
5. Run "docker-compose down"
6. Then bring Sist2 back up using "docker-compose up -d"
7. Make sure frontend has started
8. Go to frontend URL (note: I am using a custom url with NPM, not an ip address)
9. Get the error...

```
sist2 web module encountered an error while connecting to Elasticsearch. See server logs for more information.
```

Here are the logs:

```
07/27/2023 7:43:16 PM
2023-07-28 00:43:16 [DEBUG] Fetched search backend options for writing
07/27/2023 7:43:16 PM
2023-07-28 00:43:16 [INFO] Starting frontend /root/sist2 web --bind=0.0.0.0:4093 --tagline= --lang=en --es-url=http://es:9200 --es-index=writing-index /sist2-admin/scan-writing-books-2023-07-27 01:36:19.067053.sist2 /sist2-admin/scan-writing-reference-2023-07-27 01:39:27.329273.sist2
07/27/2023 7:43:35 PM
INFO:     192.168.192.23:36224 - "PUT /api/frontend/writing HTTP/1.1" 200 OK
07/27/2023 7:43:35 PM
INFO:     192.168.192.23:36236 - "POST /api/frontend/writing/stop HTTP/1.1" 200 OK
07/27/2023 7:43:36 PM
2023-07-28 00:43:36 [DEBUG] Fetched search backend options for writing
07/27/2023 7:43:36 PM
2023-07-28 00:43:36 [INFO] Starting frontend /root/sist2 web --bind=0.0.0.0:4093 --tagline= --lang=en --es-url=http://es:9200 --es-index=writing-index /sist2-admin/scan-writing-books-2023-07-27 01:36:19.067053.sist2 /sist2-admin/scan-writing-reference-2023-07-27 01:39:27.329273.sist2
07/27/2023 7:43:36 PM
INFO:     192.168.192.23:36242 - "POST /api/frontend/writing/start HTTP/1.1" 200 OK
```

In the browser console, I am seeing a variety of 500 errors:

```
POST https://writing.khodah.com/es 500                            chunk-vendors.js:14517     
```

And there is no output in the elasticsearch dockerlog.

I don't know if this matters, but I did have to change the address for elasticsearch in my docker to "es" rather than "elasticsearch". 

When I re-index, everything works.

**Comment by simon987** [comment]
Can you share your compose file? If you're using the one in the repository, it doesn't persist any data. So when you delete the container with `docker-compose down` you need to re-add the data to ElasticSearch.

Something like this should fix it:
```diff
  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: sist2-es
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
+  volumes:
+     - ./es-data/:/usr/share/elasticsearch/data
```

**Comment by rickcecil** [comment]
Thanks! 

I didn't know about the stop command -- but it makes sense. I imagine that is what Portainer does. Nice.

And I will add the volume and give that a try. I guess I assumed that it was creating a docker volume and storing things there. Regardless, I prefer this approach. Much appreciated.

**Comment by rickcecil** [comment]
Worked like a charm. Just need to make sure that esdata is owned by user 1000:1000, which is usually your user id... (for folks that might come across this post in the future).
