### ISSUE TITLE
Enhanced tagging capabilies

### ISSUE THREAD

**Issue by rickcecil** [simon987/sist2#401]
**Which SIST2 component is your Feature Request related to?**
Tagging

**Is your feature request related to a problem? Please describe.**
Not necessarily. I just want to make it easier to tag items and manage those tags.

**What would you like to see happen?**
- When I run a search, I want to be able to tag multiple items at the same time. 
- When I add a tag to one or multiple items, I would like to be able to add multiple tags at the same time.
- I would like a way to delete a tag so that it is removed from all items
- I would like a way to rename a tag so that it is updated on all items

**Additional context**
Happy to supply UI ideas.

**Comment by simon987** [comment]
Hi thanks for the suggestions, could you elaborate on the first point? Is the idea that you would tag all the search results at once?

And could you split this into 4 different issues - no need to use the template, it can just be that one sentence

**Comment by simon987** [comment]
Thanks @rickcecil, I'll close this issue now
