### ISSUE TITLE
Allow search in file path when using sqlite

### ISSUE THREAD

**Issue by nick008a** [simon987/sist2#402]
**Which SIST2 component is your Feature Request related to?**
web

**Is your feature request related to a problem? Please describe.**
Allow search in file path when using sqlite

**What would you like to see happen?**
Allow search in file path when using sqlite

**Comment by simon987** [comment]
implemented in [f423863](https://github.com/simon987/sist2/commit/f423863acb0848fdf3c67b78332c52061f7d9a8b)
