### ISSUE TITLE
Add .mobi file format

### ISSUE THREAD

**Issue by Code-Slave** [simon987/sist2#41]
Would be nice to support mopbi,epub. Im trying to add fulltext to my ebook/mag collection

**Comment by simon987** [comment]
I'm assuming you mean .mobi file ([Mobipocket](https://en.wikipedia.org/wiki/Mobipocket) format)?

.epub is already supported

**Comment by Code-Slave** [comment]
oops. yes mobi.

**Comment by simon987** [comment]
Okay, thank you for the suggestion.

I'm putting a lot of hours already on the 2.x.x version/rewrite so it might take a while to see this format implemented

**Comment by simon987** [comment]
Fixed in e436af7 (v2.0.0)
