### ISSUE TITLE
Question about using Python for User Scripts in 3.20

### ISSUE THREAD

**Issue by oderyn** [simon987/sist2#418]
sist2 version: 3.2

Platform (Linux or Docker, x86-64 or arm64): Docker

Elasticsearch version: 7.17.9

Love the new user scripts using Python. I am working on one now to help with tagging based on the structure of the filename. 

Using the example (https://sist2-python.readthedocs.io/en/latest/examples.html)

Would I post the entire script to the User Script textarea like so:

```
from sist2 import Sist2Index
import sys

index = Sist2Index(sys.argv[1])
for doc in index.document_iter():
    doc.json_data["tag"] = ["hamburger.#00FF00"]
    index.update_document(doc)

index.sync_tag_table()
index.commit()

print("Done!")
```

Or would it look more like this:
```
for doc in index.document_iter():
    doc.json_data["tag"] = ["hamburger.#00FF00"]
    index.update_document(doc)

index.sync_tag_table()
index.commit()

print("Done!")
```

Or something else entirely?

Thanks!

**Comment by simon987** [comment]
are you using version 3.2.X ?

The documentation on github is for 3.2 (which is not yet *officially* released but I believe you can get it using the `x64-linux` docker tag)

**Comment by oderyn** [comment]
I am showing version 3.2.0 in my Debug info. Here's the full info:

Label | Value
-- | --
version | 3.2.0
platform | x64_linux_docker
debugBinary | false
sist2CommitHash |  
esIndex | sist2
tagline | Lightning-fast file system indexer and search tool
dev | false
mongooseVersion | 7.7
esVersion | 7.17.9
esVersionSupported | true
esVersionLegacy | false

**Comment by simon987** [comment]
that's odd

Where are you entering the script code? It should be a form that looks like this:

![image](https://github.com/simon987/sist2/assets/7120851/4778cd70-689b-417a-aad2-5a8134faa7d7)

**Comment by oderyn** [comment]
I did not actually have a screen that looked like that. It was still the user scripts box on the index. 

However, I just took it all down and deleted state.db as it was throwing an error. 

I've lost my indexes, so will need to rebuild before I can test again, but I am now seeing the screen in your screenshot. I will report back here shortly.

**Comment by oderyn** [comment]
And now it works. :)

I appreciate the assist.

I am definitely glad it was that easy and sorry I had to bug you about it. 

Now I gotta try out my own scripts. 

This looks like a great new feature!

**Comment by simon987** [comment]
no worries!
