### ISSUE TITLE
Index: Cannot Connect to ES for index, can for Backend creation.

### ISSUE THREAD

**Issue by dpieski** [simon987/sist2#420]
**Device Information (please complete the following information):**
 - Deployment: `[Linux, Linux ARM64 or Docker]` Docker
 - SIST2 Version: `[e.g., v2.9.0]` 3.3.0
 - Elasticsearch Version *(if relevant)* : `` 8.7.1

**Command with arguments** 

```powershell
 [ADMIN ] Starting sist2 command with args ['/root/sist2', 'index', '/sist2-admin/scan-Firm-2023-09-06 19:35:30.212114.sist2', '--threads=14', '--es-url=https://elastic:password@search.DOMAIN.com:9200', '--es-index=sist2', '--batch-size=200', '--es-insecure-ssl', '--incremental-index', '--json-logs', '--very-verbose']
```

![image](https://github.com/simon987/sist2/assets/3300522/11321649-4b94-4f4b-81fe-83aa33bb7821)

**Describe the bug**

```powershell
2023-09-06 22:14:56 [ERROR web.c] CURL Error: SSL: no alternative certificate subject name matches target host name 'search.DOMAIN.com'
2023-09-06 22:14:56 [FATAL elastic.c] Could not get ES version
```

**Expected behavior**

When es_insecure is selected- use it instead of overwriting because of `https` in the domain name.

**Actual Behavior**

```powershell
2023-09-06 22:14:56 [DEBUG cli.c] arg es_url=https://elastic:PASSWORD@search.DOMAIN.com:9200
...
2023-09-06 22:14:56 [DEBUG cli.c] arg es_insecure_ssl=1
```

**Comment by simon987** [comment]
Should be fixed in 31646a2747ea7c31336da2f9eb12aa4299df1220
