### ISSUE TITLE
Unfetched PDF OCR retourncode for already existing OCR

### ISSUE THREAD

**Issue by pbaumi-at** [simon987/sist2#422]
sist2 version: 3.1.4
Platform: Docker x86-64
Elasticsearch version: 7.17.9
Command with arguments:
 ` ['/root/sist2', 'scan', '/data/XXX', '--threads=6', '--thumbnail-quality=50', '--thumbnail-count=1', '--thumbnail-size=552', '--content-size=32768', '--output=/sist2-admin/scan-home-XXX-2023-09-14 08:48:22.028251.sist2', '--depth=-1', '--archive=recurse', '--mem-buffer=2000', '--incremental', '--name=home-XXX', '--ocr-lang=deu', '--ocr-ebooks', '--treemap-threshold=0.0005', '--json-logs', '--very-verbose']"}`

Issue: Scan Task stops working after receiving error
```
FZ: OCR Disabled in this build
FZ: aborting process from uncaught error!
Child process terminated with status code 1
```

Tasks stays alive without further process. No cpu-usage on OS visible, no log entries until manual kill of the process (waited already 26 minutes. Process Termination in under 1 second. Same with one ore multiple threads.

Affected files already contain OCRed data (done with ocrmypdf / tesseract).

attachment:
[sist2-89193f74-1f17-41d9-961b-b110352248b9_anonym.log](https://github.com/simon987/sist2/files/12607192/sist2-89193f74-1f17-41d9-961b-b110352248b9_anonym.log)

If I start the indexing task without the ebook option, I receive a different error:
```
{"sist2-admin": "Starting sist2 command with args ['/root/sist2', 'scan', '/data/XXX/Dokumente', '--threads=6', '--thumbnail-quality=50', '--thumbnail-count=1', '--thumbnail-size=552', '--content-size=32768', '--output=/sist2-admin/scan-home-pbaumgartner-2023-09-14 09:38:34.063120.sist2', '--depth=-1', '--archive=recurse', '--mem-buffer=2000', '--incremental', '--name=home-pbaumgartner', '--ocr-lang=deu', '--treemap-threshold=0.0005', '--json-logs', '--very-verbose']"}
{"thread": "T0", "datetime": "2023-09-14 09:38:34", "level": "WARNING", "filepath": "main.c", "message": "Could not open original index for incremental scan: /sist2-admin/scan-home-XXX-2023-09-14 09:38:34.063120.sist2. Will not perform incremental scan."}
{"stderr": "**You must specify at least one of --ocr-ebooks, --ocr-images**"}
{"sist2-admin": "Save last_index_date=2023-09-14 09:38:34.070112"}
{"sist2-admin": "Remove self.job.previous_index_path='scan-home-XXX-2023-09-14 09:34:09.796281.sist2'"}
```
Resolution to this error: missing slash at the end of the folder --> worked with /data/XXX/Dokumente**/**

**Comment by simon987** [comment]
See #417
