### ISSUE TITLE
support CLIP embedding for images

### ISSUE THREAD

**Issue by nick008a** [simon987/sist2#424]
**Which SIST2 component is your Feature Request related to?**
index

**Is your feature request related to a problem? Please describe.**
The CLIP  image embedding can be used for finding images that looks (or conceptually) similar to user given text or image. This will bring a lot of interesting use cases.

**What would you like to see happen?**
https://github.com/photoprism/photoprism/issues/1287

**Additional context**
embeddings can be stored into qdrant (or #425) as it has better support on large-sized vector database compared to sqlite or elasticsearch.

**Comment by simon987** [comment]
Hi, CLIP embeddings are already supported in the master branch (not yet officially released)

You can create a script in the User Script tab using the CLIP template and add it in the job to enable it.

It supports text prompts and KNN ("find more images like this" button)

**Comment by curtwagner1984** [comment]
> Hi, CLIP embeddings are already supported in the master branch (not yet officially released)
> 
> You can create a script in the User Script tab using the CLIP template and add it in the job to enable it.
> 
> It supports text prompts and KNN ("find more images like this" button)

Can you please elaborate on how to do this, where to start?

**Comment by simon987** [comment]
> Can you please elaborate on how to do this, where to start?


If you are using sist2-admin,

1. Go to the User Scripts tab
2. Enter the name of the new script (ex. "clip") and select the CLIP template
3. Go to the job where you want to enable CLIP embeddings, select the created script in the list
4. re-index
