### ISSUE TITLE
leading character chopped off when scanning /

### ISSUE THREAD

**Issue by meonkeys** [simon987/sist2#426]
**Device Information (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS 64-bit desktop
 - Deployment: Docker
 - Browser *(if relevant)*: `Firefox`
 - SIST2 Version: `v3.1.4`
 - Elasticsearch Version *(if relevant)* : `7.17.9`

**Command with arguments** 
n/a, I used the default `docker-compose.yml` from [here](https://github.com/simon987/sist2#using-docker-compose-windowslinuxmac)

Only change I made was mounting my Documents folder at `/host` like so:

`/home/user/Documents:/host:ro`

**Describe the bug**
I just noticed the file paths from the root (in the container) are missing the first character (and the leading slash, although that's less important).

**Steps To Reproduce**
Please be specific!
1. Go to http://localhost:4090
2. Click on the icon to the left of `Filter path`

**Expected behavior**
List of root folders shown.

**Actual Behavior**
Paths are missing leading slash and first character. `oot/`, `ost/` and `tc/` appear instead of `/root/`, `/host/`, and `/etc/`, for example.

**Screenshots**
![Screenshot from 2023-09-20 18-26-47](https://github.com/simon987/sist2/assets/50639/af019026-7ef0-4e40-a583-53d8f88210f3)

**Additional context**
This also appears to impact viewing files. For example, say I have an image in my search results. If I click on that image to view the original, the path shows up as `[JOBNAME]/ost/image.png` instead of `[JOBNAME]/host/image.png`.

**Comment by simon987** [comment]
hi, which search backend are you using? (elaticsearch or sqlite)

**Comment by meonkeys** [comment]
elaticsearch

**Comment by meonkeys** [comment]
Huh, interesting: I deleted and re-created my index, this time setting Path to `/host`. The filter path dialog now looks proper, like I'd expect... showing full directory names under `/host` (which I've mounted via Docker to `~/Documents` on my Docker host).

I did notice all the folder names are lowercased, but so far it seems to work fine.

**Comment by simon987** [comment]
Thank you, there is a bug when the scan path is `/`, should be fixed in https://github.com/simon987/sist2/commit/33ae585879834d91797e982621ac78b42cae8adc
