### ISSUE TITLE
Show full path of files in the result

### ISSUE THREAD

**Issue by andreapx** [simon987/sist2#429]
sist2 version: 3.1.4

Platform (Linux or Docker, x86-64 or arm64): Docker

Elasticsearch version: 7.17.9 

Hi,
is it possible to show the full path of the file or, even better, open the containing folder directly in Windows Explorer?
Also: is it possible to search for part of the words? I've noticed that if I search for a portion of the word (even if it's long and unique), it doesn't return any result.
THANKS!!!

**Comment by andreapx** [comment]
> Hi, where would the full path be displayed? You can click on the file name to have sist2 serve the file from disk.

Clicking the link downloads the files, it doesn't open it directly from it's path (that would be wonderful!!!

> And you can do partial queries by enabling the "fuzzy" checkbox (elasticsearch only)

Oh, I've missed it, thanks!

**Comment by simon987** [comment]
As far as I know, modern browsers will not let you link to local files. And there is no guarantee that the full path is the same for sist2 as for the user (the file could be on a remote computerz network drive etc. Especially with docker)

You can try to set the redirect URL to

`file:///path/to/index/root/`

**Comment by andreapx** [comment]
> the file could be on a remote computer, network drive etc. Especially with docker
Yes, you're right.
A function could be a remapping: the path of the sist2 /path/to/file could be translated and shown to the user as /addedPath/path/to/file. Even if the browser can't open the file, knowing the path it would be easy for the user to go there manually (or copying/pasting it).
Just an idea.

**Comment by simon987** [comment]
And where would this full path be displayed?

**Comment by andreapx** [comment]
> And where would this full path be displayed?

Maybe just underneath every single result

**Comment by simon987** [comment]
Implemented in [b8c905b](https://github.com/simon987/sist2/commit/b8c905bd648ff18ebe12e2f6b2622fea4dce57a4) (v3.3.5)

You can enable it in Configuration -> featured fields template -> type `${doc.indexRoot}${doc.path}/`

![image](https://github.com/simon987/sist2/assets/7120851/2eafe653-8af7-4347-8d94-2d4ee1a0c662)

**Comment by simon987** [comment]
can you check logs/frontend-default.log

**Comment by andreapx** [comment]
Autch, I'll try, last time it took several hours.

**Comment by andreapx** [comment]
It seems that it can't create the index:
```
[ADMIN ] Starting sist2 command with args ['/root/sist2', 'scan', '/nas_shared/', '--threads=1', '--thumbnail-quality=50', '--thumbnail-count=1', '--thumbnail-size=552', '--content-size=32768', '--output=scan-test_job-2023-10-04 05:44:55.037532.sist2', '--depth=-1', '--archive=recurse', '--mem-buffer=2000', '--incremental', '--name=test_job', '--treemap-threshold=0.0005', '--json-logs', '--very-verbose'] [ERROR ] Invalid value for --thumbnail-quality argument: 50. Must be within [2, 31].
 [ERROR ] free(): invalid pointer
 [ADMIN ] Process returned non-zero exit code (-6)
```

Should I delete the old one and try again?

**Comment by simon987** [comment]
It's probably because you're upgrading from 3.1.4. There has been a lot of breaking changes, both in sist2-admin and sist2. You will have to delete the sist2-admin folder and start from scratch because unfortunately there are no migration scripts for this version

**Comment by andreapx** [comment]
Ok ok, I'lldo that!
Thanks!
