### ISSUE TITLE
html files not parsed completely.

### ISSUE THREAD

**Issue by hedonagenda** [simon987/sist2#432]
I have several html files, mostly tweets saved with [singlefile](https://github.com/gildas-lormeau/SingleFile) which are not parsed completely. Only the first tweet is extracted. While I know that twitter isn't the best example, maybe its happening with other types of content too? Also these files are self extracting self contained html files if that's relevant.

Right now I'm trying to connect a debugger to sist2 executable to see exactly what content is taken out of html files as I couldn't open the sqlite database probably because it is a slightly modified format (custom extension). 

If anyone else is finding that some html content is getting missed please chime in!

**Comment by simon987** [comment]
what is the value of `--content-length` ? 

And you should be able to open the .sist2 index with any up-to-date sqlite viewer.

**Comment by simon987** [comment]
If you click on the (i) icon in the UI it should display the entire content extracted by sist2

**Comment by hedonagenda** [comment]
oh i though (i) gave just the context of the keyword. 

the content length is the entire size of the html file. at least that's what i see when i open it with a server. So its shows to be like 1mb. 
but when I click on (i) it starts with `:root --sf-img-6: url(` and goes on to list links in base64 like this: `data:image/jpeg;base64`

**Comment by simon987** [comment]
no i meant your value of the `--content-size` argument, specified in sist2-admin here: 

![image](https://github.com/simon987/sist2/assets/7120851/85fbc03d-426e-430f-aac2-079a275b7da1)

By default, sist2 only extracts the first 32kb of text from files

**Comment by hedonagenda** [comment]
its 32768. Oops should've disabled it.
