### ISSUE TITLE
extra spaces in result when ocr chinese

### ISSUE THREAD

**Issue by ffchung** [simon987/sist2#443]
**Which SIST2 component is your Feature Request related to?**

Scan with ocr image and ocr ebook

**Is your feature request related to a problem? Please describe.**

Ref to : https://github.com/tesseract-ocr/tesseract/issues/991

I need to pass the setting preserve_interword_spaces=1 to tesseract.

**What would you like to see happen?**

chinese ocr with extra spaces.

**Additional context**

**Comment by simon987** [comment]
Thanks,

Fixed in [2936240](https://github.com/simon987/sist2/commit/2936240df8b25a15306fe446eaae10ab3bb58300)

![image](https://github.com/simon987/sist2/assets/7120851/77efeea7-3ab1-46fe-a9ad-513182271ab8)

Before:

```
伦敦 楼 房 发 生火 灾 中 使 馆 关 注 : 暂 无 中 国 公民 受伤
```

After:
```
伦敦楼房发生火灾中使馆关注 : 暂无中国公民受伤
```
