### ISSUE TITLE
Toggle or configure minimum characters limit for file

### ISSUE THREAD

**Issue by SystemZ** [simon987/sist2#450]
**Which SIST2 component is your Feature Request related to?**
Index

**Is your feature request related to a problem? Please describe.**
For images with small amount of text, like memes - indexing is cutting off files at hard-coded required limit for characters/words.

**What would you like to see happen?**
I would like to configure this threshold or be able to disable it

**Additional context**
I asked related question on discord
https://discord.com/channels/1160913303464333372/1160913303464333375/1190888265918713908

**Comment by simon987** [comment]
Changed to 3 char in [ae317e5](https://github.com/simon987/sist2/commit/ae317e590d3b5d658f502b5f483375d09effc423)
