### ISSUE TITLE
sist2-admin should handle auth argument errors

### ISSUE THREAD

**Issue by Mitmischer** [simon987/sist2#453]
**Which SIST2 component is your Feature Request related to?**
web

**Is your feature request related to a problem? Please describe.**
I had some struggle setting up the web and found some obstacles along the way.
The problem is that I set up both "basic auth" and "basic auth for tagging" which are mutually exclusive.

**What would you like to see happen?**
* When pressing the start button for a frontend, did not report when the process could not be started. It should do so. 
* When the process could not be started, the web ui should report the log. As of now, the log is not even accessible in the docker logs (which would be another appropriate place).
* The UI should check for invalid values (for example, "Basic auth in user:password format" and "Basic auth in user:password format for tagging" being mutually exclusive.
* When the process is not running, the web UI should not make stop button available.
* Pressing the stop button when the process is not running results in an exception (check the docker logs). This exception should be forwarded to the ui.

**Additional context**
sist2 is running in docker.

**Comment by simon987** [comment]
Fixed in [aff69fb](https://github.com/simon987/sist2/commit/aff69fb3eb0abf3103428118cd4795f07e1b24a5) and 08b63231768c8b8d1be74b1f23d1dbca08825126

**Comment by Mitmischer** [comment]
Thank you! And keep up the good work :)
