### ISSUE TITLE
custom web interface

### ISSUE THREAD

**Issue by mvezio** [simon987/sist2#464]
**Which SIST2 component is your Feature Request related to?**

web
**Is your feature request related to a problem? Please describe.**

edit web interface (custom html)
**What would you like to see happen?**

i wish to can edit web interface 
**Additional context**

**Comment by simon987** [comment]
Is there a specific thing you would like to be able to change?

**Comment by mvezio** [comment]
Please i wish to have complete control of web gui in html

Il giorno mar 30 gen 2024 alle 15:35 simon987 ***@***.***> ha
scritto:

**Comment by simon987** [comment]
Sorry I can't help with that. You can customize any of the frontend files in https://github.com/simon987/sist2/tree/master/sist2-vue and recompile the project if you wish to have complete control

**Comment by mvezio** [comment]
sorry, but in which files are the messages found, for example the one on
the navbar "lightning-fast file system ..."?? Thank you

Il giorno mar 30 gen 2024 alle ore 16:03 simon987 ***@***.***>
ha scritto:

**Comment by dpieski** [comment]
Github has a search feature. Type in the line you want to find and it will search the repository for it... Then just read through them to find the location you are looking for.

**Comment by mvezio** [comment]
HI
sorry for the inconvenience but I have a fairly significant problem during
the scanning phase

I activated verbose mode, and I see that for .docx files the error "could
not read archive: unrecognized archive format" appears
instead, for some other extensions (for example dwg) the error is
avformat_open_input() returned... : invalid data found when processing
input.

Do these errors affect the final result? thank you in advance.

Il giorno gio 1 feb 2024 alle ore 17:00 Andrew ***@***.***>
ha scritto:

**Comment by Koshux** [comment]
Has anyone been able to use bind mounts to be able to use HMR or the `watch.sh` to see changes deployed on save?
