### ISSUE TITLE
chrome / reverse proxy issue

### ISSUE THREAD

**Issue by lakemike** [simon987/sist2#47]
sist2 version: v2.1.0
Platform: Docker
Command: `docker run -d --net=bridge --rm --name sist2 -p 4090:4090 -v "$SRVDIR":"/docs" -v $IDXBASE/idx/:"/idx" -t simon987/sist2:2.1.0 web --very-verbose --bind 0.0.0.0:4090 --es-url http://192.168.86.11:9200 ./idx/$IDXDIR/`

Hi,
With v1.3.3 using chrome, I could access sist2 directly (URL with IP address) or using traefik as reverse proxy (e.g. https://sist2.subdomain.domain.org/). On v2.1.0 at least for PC or MacOs versions of chrome, only the direct access URL works. The proxied URL starts to load the interface, but then stops displaying a blue bar below the input mask. Seems to be related to chrome because it works with Safari.

Kind regards,
lakemike

**Comment by simon987** [comment]
Hi @lakemike, can you open the Chrome dev tools (F12) and let me know if you see any errors in the console?

**Comment by lakemike** [comment]
Sure! I see this error message in the console:
```
TypeError: SORT_MODES[CONF.options.sort] is undefined js:1347:9
    search https://sist2.grautvornix.ddnss.ch/js:1347
    searchDebounced https://sist2.grautvornix.ddnss.ch/js:1408
    e https://sist2.grautvornix.ddnss.ch/js:77
    o https://sist2.grautvornix.ddnss.ch/js:77
    i https://sist2.grautvornix.ddnss.ch/js:77
```

**Comment by simon987** [comment]
Hi @lakemike, I really appreciate your detailed bug reports.
Can you please let me know if you still have the same problem on Chrome with the v2.1.1 docker image?

**Comment by lakemike** [comment]
Problem is solved! Great job!

**Comment by simon987** [comment]
Thank you for the confirmation. The problem was that previous (incompatible) client settings were saved in the browser's LocalStorage. I made it so the settings are reverted to default when that happens (e6fde38).
