### ISSUE TITLE
Add speech to text functionality

### ISSUE THREAD

**Issue by Snify89** [simon987/sist2#471]
**Which SIST2 component is your Feature Request related to?**

Scan and Index

**Is your feature request related to a problem? Please describe.**

No.

**What would you like to see happen?**

I would like to be able to index media files (audio/video) with their transcript.
This can be done (for example) by speech to text technology.

This would be a great feature!
Thank you for considering :)

**Comment by simon987** [comment]
this is already supported by the Whisper script, check https://github.com/simon987/sist2/blob/master/docs/scripting.md
