### ISSUE TITLE
"Duplicate field content" error during index step

### ISSUE THREAD

**Issue by lakemike** [simon987/sist2#48]
sist2 version: 2.1.0
Platform: Docker
Command with arguments:  
```
docker run --net=bridge --rm --name sist2 \
   -v "$SRVDIR":"/docs" \
   -v $IDXBASE/idx/:"/idx" \
   -t simon987/sist2:$VERSION \
   index --very-verbose --force-reset --batch-size=100 --es-url=http://192.168.86.11:9200 ./idx/$IDXDIR/ 2>&1 | tee ./index.out
```

I see very few of these errors during indexing:
```
[7F0672D8A540]^[[01;33m [2020-05-03 09:45:08] [ERROR elastic.c] {
        "index":        {
                "_index":       "sist2",
                "_type":        "_doc",
                "_id":  "df30616f-de8d-4eb1-93b6-2d823bff9eef",
                "status":       400,
                "error":        {
                        "type": "parse_exception",
                        "reason":       "Failed to parse content to map",
                        "caused_by":    {
                                "type": "json_parse_exception",
                                "reason":       "Duplicate field 'content'\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@72fea466; line: 1, column: 629]"
                        }
                }
        }
}
```

**Comment by simon987** [comment]
Hi, could you give me the output of this command please?
`sist2 index --print ./idx/$IDXDIR/ | grep 'df30616f-de8d-4eb1-93b6-2d823bff9eef'`

**Comment by lakemike** [comment]
Here you go:
`{"_id":"df30616f-de8d-4eb1-93b6-2d823bff9eef","_index":"sist2","_type":"_doc","_source":{"index":"d0029246-a94d-4609-bbc8-4f46c3a4eacf","mime":"video/mp4","size":48737934,"mtime":1380524547,"extension":"mp4","name":"Myshkin Ingawale _ TED 2012 _ A blood test without bleeding","path":"03 INFORMATION/30 OTHER LITERATURE/Digital, social media, mHealth, ePharma/mHealth","videoc":"png","width":400,"height":400,"audioc":"aac","title":"TED: Myshkin Ingawale (2012 University)","artist":"TED","album":"TEDTalks","content":"To learn more about this speaker, find other TEDTalks, and subscribe to this Podcast series, visit www.TED.com Feedback: contact ted.com","genre":"Podcast","duration":403,"bitrate":967214,"content":"To learn more about this speaker, find other TEDTalks, and subscribe to this Podcast series, visit www.TED.com Feedback: contact ted.com","thumbnail":"0400,0400"}}`

**Comment by simon987** [comment]
That's very odd, I'm assuming that there is duplicate comment tags (perhaps `comment` and `Comment` ?). If you don't mind @lakemike can you run `ffprobe -show_format /path/to/Myshkin Ingawale _ TED 2012 _ A blood test without bleeding.mp4`?

**Comment by lakemike** [comment]
Pls see below:
`ffprobe version 4.1.4-1~deb10u1 Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x559e0e06cec0] stream 0, timescale not set
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from './03 INFORMATION/30 OTHER LITERATURE/Digital, social media, mHealth, ePharma/mHealth/Myshkin Ingawale _ TED 2012 _ A blood test without bleeding.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isom
    creation_time   : 2012-03-14T23:39:05.000000Z
    podcast         : 1
    media_type      : 0
    title           : TED: Myshkin Ingawale (2012 University)
    artist          : TED
    date            : 2012
    album           : TEDTalks
    comment         : To learn more about this speaker, find other TEDTalks, and subscribe to this Podcast series, visit www.TED.com
                    : Feedback: contact@ted.com
    genre           : Podcast
    category        : Higher Education
  Duration: 00:06:43.12, start: 0.000000, bitrate: 967 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 854x480 [SAR 1280:1281 DAR 16:9], 867 kb/s, 24 fps, 24 tbr, 24 tbn, 48 tbc (default)
    Metadata:
      creation_time   : 2011-08-05T17:30:09.000000Z
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 95 kb/s (default)
    Metadata:
      creation_time   : 2012-03-14T23:39:06.000000Z
      handler_name    : GPAC ISO Audio Handler
    Stream #0:2: Video: png, pal8(pc), 400x400, 90k tbr, 90k tbn, 90k tbc
michael@idefix:/mnt/Work_Michael/DATA/Novartis/OneDrive$ cd
michael@idefix:~$ cat format_Myshkin.txt 
[FORMAT]
filename=./03 INFORMATION/30 OTHER LITERATURE/Digital, social media, mHealth, ePharma/mHealth/Myshkin Ingawale _ TED 2012 _ A blood test without bleeding.mp4
nb_streams=3
nb_programs=0
format_name=mov,mp4,m4a,3gp,3g2,mj2
format_long_name=QuickTime / MOV
start_time=0.000000
duration=403.120000
size=48737934
bit_rate=967214
probe_score=100
TAG:major_brand=isom
TAG:minor_version=1
TAG:compatible_brands=isom
TAG:creation_time=2012-03-14T23:39:05.000000Z
TAG:podcast=1
TAG:media_type=0
TAG:title=TED: Myshkin Ingawale (2012 University)
TAG:artist=TED
TAG:date=2012
TAG:album=TEDTalks
TAG:comment=To learn more about this speaker, find other TEDTalks, and subscribe to this Podcast series, visit www.TED.com
Feedback: contact@ted.com
TAG:genre=Podcast
TAG:category=Higher Education
[/FORMAT]
`

**Comment by simon987** [comment]
Thanks a lot for the help @lakemike. Please let me know if the problem still persists with the Docker image v2.1.1

**Comment by lakemike** [comment]
I can confirm that this particular error is gone with v2.1.2.
However, some others arrived:
ERROR.. (media.c) avformat_open_input() returned [2083949464] Invalid data found when processing input
ERROR.. Could not read archive: 
[ERROR ooxml.c] Got recoverable XML error while parsing document:
A lot of errors actually .. 1.1mio for 32000+ documents. ;)

**Comment by simon987** [comment]
Okay, I'm closing this issue for now. If you can, would you like to open a new issue for those errors? Thanks
