### ISSUE TITLE
Disk usage analyser?

### ISSUE THREAD

**Issue by victorhooi** [simon987/sist2#50]
Wow - this is pretty awesome =). Can't wait to try this on my NAS box.

What do you think about adding some kind of visualisation for disk usage to Sist2?

This would allow you to drill down to directories, and see where space is going. From the screenshots - it seems like Sist2 already stores the size, right? Is there enough data in the schema to create someting?

The Diskover project has some images that could show what I mean:

https://github.com/shirosaidev/diskover
https://github.com/shirosaidev/diskover-web

I was also thinking of Gnome Baobab:

https://wiki.gnome.org/Apps/DiskUsageAnalyzer
https://github.com/GNOME/baobab

or Windirstat:

https://windirstat.net/

**Comment by simon987** [comment]
Technically there is everything needed to create a disk usage visualization, I'll see what I can do

**Comment by simon987** [comment]
fixed in v2.3.0 please let me know if it works well for you
