### ISSUE TITLE
filename/title search functionality is missing

### ISSUE THREAD

**Issue by kouroshshafi** [simon987/sist2#502]
**Which SIST2 component is your Feature Request related to?**
Index and Web

**Is your feature request related to a problem? Please describe.**
I wish I could also search by filename.

**What would you like to see happen?**
An option in the search box that limits search to file names instead of the content.

**Additional context**

I often have filenames that are organized very well using their names, but the current indexing somewhat ignores filenames. an option in search like title:"XXX" would be much appreciated.
<img width="1109" alt="Screenshot 2024-11-22 at 3 35 44 PM" src="https://github.com/user-attachments/assets/5b8d3767-f9f4-4140-8e22-b42fc89e5006">

**Comment by simon987** [comment]
Hi you can already do that. Enable Advanced search in the configuration page and type `name:XXX`
