### ISSUE TITLE
stats.c: Treemap - May not handle paths with commas

### ISSUE THREAD

**Issue by dpieski** [simon987/sist2#58]
sist2 version: 2.4.0 

Platform (Linux or Docker): Docker

Elasticsearch version: 7.7.0

In stats.c you have the function csv_escape. 
in csv_escape, you 
Check if there is a comma or doublequote:
if there isn't, you just pass along the string.
If there is a doublequote, you cycle through the string and double up the doublequotes. 

But you don't do anything if there is a comma in the string. I think you should have to escape strings with commas too.

Also, if I remember correctly (and its been like 15yrs since I took C), counting starts at 0 in C and while loops check the condition before executing the loop, so I think your while loop is cutting off the first character of the string since it will not add the 'zeroth' character of the string to `*out`

**Comment by dpieski** [comment]
Also couldn't you replace the while loop with something like:

`snprintf(dst, PATH_MAX *4, "\"%s\"", str)`

Or to the `if (rfind(str, ',') ....` put the above in an else?

**Comment by dpieski** [comment]
Example from treemap.csv

![image](https://user-images.githubusercontent.com/3300522/83662635-66aff200-a58d-11ea-9ac8-d19cd51654ac.png)

See the different colors of the commas from VSC showing the different columns.
See also, the row with the commas has lost its first character "6"

**Comment by simon987** [comment]
Yeah. I meant to surround by double-quotes in the "else" part, it must have been very late when I wrote it, sorry about that. It should be fixed in v2.4.1

**Comment by dpieski** [comment]
This appears corrected. Closing.
