### ISSUE TITLE
sist2 cannot scan directories with space in name and/or some special characters

### ISSUE THREAD

**Issue by CatTheHacker** [simon987/sist2#59]
sist2 version: 2.4.0 and older

Platform (Linux or Docker): Linux (Ubuntu 20.04)
`Linux cat-Virtual-Machine 5.4.0-1012-azure #12-Ubuntu SMP Mon May 11 13:30:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
Filesystem: ext4 

Elasticsearch version: N/A

Command with arguments: 
`sist2 scan -o Sega\ Dreamcast_idx/ -t 8 -q 1 --content-size 16000000 Sega\ Dreamcast/`
output:
```bash
File not found: Sega Dreamcast/
munmap_chunk(): invalid pointer
fish: “sist2 scan -o Sega\ Dreamcast_i…” terminated by signal SIGABRT (Abort)
```

`sist2 scan -o "Sega Dreamcast_idx/" -t 8 -q 1 --content-size 16000000 "Sega Dreamcast/"`
output:
```bash
File not found: Sega Dreamcast/
munmap_chunk(): invalid pointer
fish: “sist2 scan -o "Sega Dreamcast_i…” terminated by signal SIGABRT (Abort)
```

Happens in `bash` and `fish`

**Comment by simon987** [comment]
Should be fixed in v2.4.1

**Comment by CatTheHacker** [comment]
![image](https://user-images.githubusercontent.com/31106839/83954811-0f837900-a83c-11ea-9e60-241a585eb1c8.png)
![image](https://cdn.discordapp.com/emojis/393600137798352896.gif)

**Comment by simon987** [comment]
There was a problem with special characters (`&` in this case) not being handled correctly. It should be resolved in 2.4.2, let me know

**Comment by CatTheHacker** [comment]
Seems to be working fine now, both for spaces and `&`.
![image](https://user-images.githubusercontent.com/31106839/84330862-0d8d2300-ab78-11ea-88ab-3b33983e4c8f.png)
![image](https://user-images.githubusercontent.com/31106839/84331034-a4f27600-ab78-11ea-9693-5ea211ebcdb6.png)

**Comment by simon987** [comment]
Great thank for checking
