### ISSUE TITLE
Index: User Scripts [Discussion]

### ISSUE THREAD

**Issue by dpieski** [simon987/sist2#61]
I have a few general questions about `--script-file <script>`

I see that it uses Painless Scripting Language, but what is the file type for the script? Does the script file need a specific extension? 

Also, I put all scripts in one file, not a different file for each script, right?

So something like:
```
ArrayList tags = ctx._source.tag = new ArrayList();

if (ctx._source?.genre != null) {
    tags.add("genre." + ctx._source.genre.toLowerCase())
}

Matcher m = /[\(\.+](20[0-9]{2})[\)\.+]/.matcher(ctx._source.name);
if (m.find()) {
    tags.add("year." + m.group(1))
}
```

**Comment by simon987** [comment]
> what is the file type for the script? Does the script file need a specific extension?

The file does not need any specific extension. I usually chose `.java` to get syntax highlighting in vim but it can be .txt or no extension at all

> I put all scripts in one file, not a different file for each script, right?

You can only specify one script (one file) per index.

I need to put more work on scripting documentation but in short:

The contents of your script file is executed for each document in the index while ingesting. The `ctx` variable lets you modify the document to your liking (and more importantly, add tags to the document). Let's say you want to add a special tag to files that have the .jpg extension and a have a height larger than 1920px, you could add a check in your script to do just that. Then, you can quickly filter those documents with the 'tags' tab in the UI.

**Comment by dpieski** [comment]
Thanks! I have successfully created my first tags.

**Comment by simon987** [comment]
No problem, don't hesitate if you have scripting questions, it might help me write better documentation for the feature
