### ISSUE TITLE
Index: Scripting tags hierarchy issue/question

### ISSUE THREAD

**Issue by dpieski** [simon987/sist2#64]
sist2 version: 2.4.2

Platform (Linux or Docker): docker

Elasticsearch version: 7.7.0

Command with arguments:

```powershell
docker run --rm -it --name sindex-te --network host -v $PWD/out/:/out simon987/sist2:2.4.2 index --script-file /out/te.idx/scripts.java --force-reset --batch-size 1000 --es-url http://localhost:9201 /out/te.idx
```

Script:
```java
// Script for the patent.IDS tags.
// Does the document name have "ids" in it and is the content not null? (this will not tag an IDS that is a non-OCR pdf)
if (ctx._source.name.toLowerCase().contains("ids") && ctx._source.content != null) {
    // Does the content of the document contain "information disclosure statement" or "1449/PTO" (the form name)
    if (ctx._source.content.toLowerCase().contains("information disclosure statement") 
        || ctx._source.content.contains("1449/PTO")) {
        // Add a tag of "IDS" under the "Patents" parent tag in the hierarchy
        tags.add("Patents.IDS");
        if (ctx._source.name.contains("EAR")) {
            // Add a tag of "EAR" under "IDS" 
            tags.add("Patents.IDS.EAR");
        }
    }
}
```

Result:
![image](https://user-images.githubusercontent.com/3300522/85184642-16f04c80-b256-11ea-9e58-9ed43e74a6bb.png)

Expectation:
```
+ As Filed (90)
+ Patents (616)
   |- IDS (616)
      |- EAR (87)
+ All (32655)
```

Second issue:
Selecting the box next to the following names of tags-
Check Patents > checks Patents and everything under Patents
Check All > only checks "All"
Uncheck All > unchecks everything

However:
Checking IDS (with EAR) > checks EAR
Checking ALL > Only Checks "All"
Uncheck ALL > Only Unchecks "All" (Or other top level Tags)

**Comment by simon987** [comment]
I made #65 for the other issue you brought up

There is a display issue because it's comparing `IDS (616)` =? `IDS` which are not equal. This is a weird because I remember fixing this exact issue in the past, maybe I forgot to push the changes...

As for the number in parenthesis I'm not able to make it exactly how you expect it, because of how the query to get the tags works: it's displaying the number of documents with this exact tag (not the number of documents with that tag plus all its 'children' tags). 
In your example, no tag have the "Patents" tag by itself.

Can you try with v2.4.4 (no need to re-index) and let me know if it's displayed correctly?
Thanks

**Comment by dpieski** [comment]
The display issue seems to be taken care of. 

Now, however, I don't think it is filtering by the "EAR" tag. I am guessing Tags are logical "OR"s? No matter which selection I make in the "Patents" tag tree, all three are selected and it shows all 616 results from IDS. If I have EAR selected, I would expect it to show only EAR results. 

With tags, are they logical "AND"s or "OR"s? 

I think I was expecting "AND". So, if I wanted to see all "IDS" documents "As Filed", I would select Patents > [x] IDS and [x] As Filed. But I think, since it is an "OR" I will see all documents with either a Patents.IDS tag or "As Filed" tag, correct?

**Comment by simon987** [comment]
I see,
Right now it's OR (like the mime-type tree) but obviously it would make more sense to have it with "AND". 

I'll find a way to make it work for your use case.

**Comment by simon987** [comment]
Can you let me know if v2.5.1 works for you?

**Comment by dpieski** [comment]
I think it is working how I would expect it to.

**Comment by simon987** [comment]
Thanks, I'm closing this issue for now but you can reopen if needed
