### ISSUE TITLE
Tag tree problem

### ISSUE THREAD

**Issue by simon987** [simon987/sist2#65]
sist2 version: 2.4.2

See #64 

Selecting the box next to the following names of tags-
Check Patents > checks Patents and everything under Patents
Check All > only checks "All"
Uncheck All > unchecks everything

However:
Checking IDS (with EAR) > checks EAR
Checking ALL > Only Checks "All"
Uncheck ALL > Only Unchecks "All" (Or other top level Tags)

**Comment by simon987** [comment]
I'm not sure I understand @dpieski, can you elaborate on what you are expecting to happen?

**Comment by dpieski** [comment]
The "however" section does not Uncheck the subtags, it only unchecks the top level tag. 

Right now, if you have a top level tag selected, then you select "All", then deselect "All" the top level tag will be deselected. 

However, if you have a second- or third-level tag selected, then you select "All", then deselect "All" the second- and third-level tags will _not_ be deselected.
