### ISSUE TITLE
Scan: MuPDF errors?

### ISSUE THREAD

**Issue by dpieski** [simon987/sist2#73]
sist2 version: 2.6.0

Platform (Linux or Docker): docker

Command with arguments: 
`docker run -it --name sscan-eagle-0715 -v theeagle:/files -v $PWD/out/:/out simon987/sist2:2.6.0 scan --verbose --threads 2 --name TheEag --content-size 131072 /files -o /out/theeag0715.idx`

If the issue is related to the `scan` module, please attach the files necessary to reproduce the error or email them to me[at]simon987.net.

I have a number of "Warnings" with the warning as "FZ: [?]"

![image](https://user-images.githubusercontent.com/3300522/87582250-c2e35700-c69f-11ea-8cd7-1f643f9868bc.png)

Any ideas how I can see what the warning is instead of just the [?] box?
Either I am getting a whole lot of the same warnings or all pdf warnings are returned as [?].

**Comment by simon987** [comment]
IIRC this is the error message printed as-is from MuPDF, I'll try to reproduce/investigate but I'll probably end up just filtering out those messages if I can't get any human-readable information for those errors

**Comment by simon987** [comment]
I was using the wrong function in some log calls, it should display the normal error messages now
