### ISSUE TITLE
Suggestion: Thumbnails for docx\pptx

### ISSUE THREAD

**Issue by dpieski** [simon987/sist2#74]
Could you use the thumbnail that Office makes automatically? If the files doesn't have one, just pass over it. But if it does have one, use the thumbnail that already exists.

If you open a docx/pptx that has a thumbnail, the thumbnail is located at `\docProps\thumbnail.jpeg`

**Comment by simon987** [comment]
Great suggestion! I didn't know that was a thing, thanks

Is implemented in v2.6.1
