### ISSUE TITLE
Copy /tags/ when scanning with --incremental

### ISSUE THREAD

**Issue by simon987** [simon987/sist2#76]

**Comment by dpieski** [comment]
I am wondering if this is the issue I just ran into?

Command: `docker run --rm -it --name $($index -f $counter) -v theeagle:/files -v ${location}:/out simon987/sist2:2.6.0 scan --threads 4 --name TheEag --content-size 131072 --incremental=/out/$oldindex /files -o /out/$newindex`

(process:1): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed
[7F0A39118840] [2020-07-15 22:35:29] [FATAL store.c] Error while opening store: No such file or directory (/out/theeag0715.idxthumbs)

**Comment by simon987** [comment]
> I am wondering if this is the issue I just ran into?

I don't think so, the "GLib-CRITICAL" can be safely ignore (and was fixed in v2.6.1). The "No such file or directory" is probably a bug in the way the -o argument is passed (try using `/out/$newindex/` for now) I'll create a new issue for that
