### ISSUE TITLE
access limited to data based on file permissions

### ISSUE THREAD

**Issue by bbrendon** [simon987/sist2#95]
Enhancement request.  Point this to cifs/nfs shares and the results would only show what the user has access to. I suppose that would also require some login system.

**Comment by simon987** [comment]
Hi, thanks for the suggestion, this will require some more thinking but I'm sure I can make that work somehow

**Comment by simon987** [comment]
Sorry for the lack of response, I looked in to it and it would be too much work to implement, so I'm not going to implement that feature in the near future
