### ISSUE TITLE
Allow clicking on treemap to drill down to specific directories

### ISSUE THREAD

**Issue by victorhooi** [simon987/sist2#96]
I just saw you added a demo to https://sist2.simon987.net/ - that is super awesome =).

I also plugged your project in r/datahoarders and r/selfhosted - hopefully you'll get some more traffic. 

With the treemap in your stats page - do you think it's possible to allow drill-down to specific folders by clicking on them.

What I mean is - currently it's a static image for the top level - but what I mean is - is it possible to allow you to click on folders, and then show the treemap at that level? (And then a button to go back up).

[WinDirStat](https://windirstat.net/), or the [Gnome Disk Usage Analyzer](https://wiki.gnome.org/Apps/DiskUsageAnalyzer) probably give a good idea of what I mean (and the Gnome Disk Usage Analyzer also presents the data quite nicely).

(Also, the "Enlarge" text zooms into an image, but it still shows "Enlarge" after, when you zoom out - small thing - but maybe change it to "Enlarge", then "Shrink" etc.).

**Comment by simon987** [comment]
Thanks for the suggestion.

Unfortunately that's not really possible without rewriting the treemap graph from scratch, and that's not something I'm willing to spend my time on right now, sorry.
