### ISSUE TITLE
Web Feature Request: Show Thumbnail in Information Popup

### ISSUE THREAD

**Issue by dpieski** [simon987/sist2#99]
sist2 version: 2.8.0

It could be useful if when clicking on the information icon to get the popup, the thumbnail is included.

This information icon: 
![image](https://user-images.githubusercontent.com/3300522/90578356-bc596b00-e188-11ea-9ad2-dcbf7d102d50.png)

Also, ~~would you be able to take the `mtime` and make it read out like a standard data/time?~~ (See #100)

**Comment by simon987** [comment]
Good idea, thanks for the suggestions

**Comment by simon987** [comment]
Fill be available in v2.8.2
